
<VERSION_FORMAT>               V06.000

# Contexte <CDG 4> : Export de l'exercice ARR2_4_3

<EXERCICE>                     ARR2_4_3;CAUTR;ORAGES
     # Description
     <DATES>                   10:00;12:00;SEMAI;09/01/2015
     <ORGANISATION>            APPRO;LFPG;08;EL
     <VISAS_MAESTRO>           CDG
     <METEO_GLOBALE>           9;986;0
     <SECTEUR>                 RB
     <SECTEUR>                 RA
     <SECTEUR>                 RC;DC;RD
     <ACTION_EXO>              ACD;ILS09L;CDG;10:00;12:00;ILS09L
     <ACTION_EXO>              ACD;ILS08R;CDG;10:00;12:00;ILS08R
     <ACTION_EXO>              ACD;AXE07B;CDG;10:00;12:00;AXE07B
     <ACTION_EXO>              ACD;ITMEL;CDG;10:00;12:00;ITMEL
     <ACTION_EXO>              ACD;ELNEW;CDG;10:00;12:00;ELNEW
     <ACTION_EXO>              ACD;CONTEL;CDG;10:00;12:00;CONTEL
     <ACTION_EXO>              ACD;LFOB4500;CDG;10:00;12:00;OB4500
     <CONFIG_PISTE>            LFPG;E;PARI
     <CONFIG_PISTE>            LFPB;E;PARI
     <CONFIG_PISTE>            LFPO;E;PARI
     <CONFIG_PISTE>            LFPN;E;PARI
     <CONFIG_PISTE>            LFPV;E;PARI
     <CONFIG_PISTE>            LFOB;E;PARI
     <CONFIG_PISTE>            LFPT;E;PARI
     <CONFIG_PISTE>            LFPC;E;PARI
     <CONFIG_PISTE>            LFAP;E;PARI
     # Trafic : 124 PLN(s)
     <PLN>                     SAS579;B736;ESSA;LFPG;09:45:41;VCAG;MMOY;DEPOT
          # Identifiant        101
          <PLN_SUITE>          SAS;ETMOY;IFR;BASE;ESSA;1
          <NIVEAUX>            390;300;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_R;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:35:02;09:36:12;09:41:14;09:43:42;09:44:36;09:45:42
          # Niveaux            300;275;177;150;150;150
          # Vitesses           280;280;280;330;330;330
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:36;09:37;09:41;09:43;09:44;09:45;09:53
          # Niveaux_STIP       300;321;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000001
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:21;101;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;126.430
          # Transfert          
          # Secteurs_traverses 
          # Heures_entree      
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           3501
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR715J;E190;EGBB;LFPG;09:54:14;VCAG;MMOY;DEPOT
          # Identifiant        102
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EGBB;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_R;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           09:42:52;09:44:24;09:45:46;09:54:14;09:55:48
          # Niveaux            250;240;240;100;100
          # Vitesses           300;310;310;250;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:38;09:39;09:40;09:42;09:44;09:46;09:46;09:54;09:56;10:02
          # Niveaux_STIP       250;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000002
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:29;102;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;126.430
          # Transfert          10:00:00;121.155
          # Secteurs_traverses 18;TP;RB
          # Heures_entree      09:42:52;09:43:16;09:55:50
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2201
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1383;A320;LKPR;LFPG;09:49:35;VCAG;MMOY;DEPOT
          # Identifiant        103
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LKPR;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_R;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:39:14;09:41:12;09:45:10;09:47:28;09:48:26;09:49:36
          # Niveaux            300;280;194;150;150;150
          # Vitesses           300;310;300;308;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:39;09:41;09:45;09:46;09:47;09:49;09:56
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000003
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:24;103;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;126.430
          # Transfert          
          # Secteurs_traverses 
          # Heures_entree      
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           6601
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     DAL98;B763;KDTW;LFPG;09:59:35;VCAG;MMOY;DEPOT
          # Identifiant        104
          <PLN_SUITE>          DAL;ETLON;IFR;BASE;KDTW;1
          <NIVEAUX>            370;260;
          <DEPART_BALISE>      INGOR
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            INGOR;LUKIP;KOLIV;M0PAR
          # Estimees           09:48:30;09:52:28;09:59:36;10:00:38
          # Niveaux            260;220;108;100
          # Vitesses           290;330;290;262
          <FL_BALISES>         220;100;;
          # Balises_STIP       INGOR;LUKIP;LUKI;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:48;09:51;09:51;09:59;10:00;10:06
          # Niveaux_STIP       260;370;247;120;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000004
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:36;104;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00
          # Transfert          10:00:00;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      09:48:30;10:00:40
          # Secteurs_traverses_STIP JS;UK;TP;RB
          # TOD                 
          # Code_SSR           0201
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     KLM26P;B737;EHAM;LFPG;09:53:35;VCAG;MMOY;DEPOT
          # Identifiant        105
          <PLN_SUITE>          KLM;ETMOY;IFR;BASE;EHAM;1
          <NIVEAUX>            290;290;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_R;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:42:54;09:44:06;09:49:14;09:51:38;09:52:30;09:53:36
          # Niveaux            290;265;166;150;150;150
          # Vitesses           280;280;280;330;330;330
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:44;09:45;09:49;09:51;09:52;09:53;10:01
          # Niveaux_STIP       290;290;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000005
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:29;105;PARI;SUP
          # Transfert          10:00:00;121.155
          # Secteurs_traverses AP;TE;RB
          # Heures_entree      09:42:54;09:44:12;09:53:38
          # Secteurs_traverses_STIP AP;TE;RB
          # TOD                 
          # Code_SSR           0101
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     CES553;A332;ZSPD;LFPG;09:55:35;VCAG;MMOY;DEPOT
          # Identifiant        106
          <PLN_SUITE>          CES;ETLON;IFR;BASE;ZSPD;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_R;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:45:14;09:47:14;09:51:12;09:53:24;09:54:22;09:55:36
          # Niveaux            300;280;207;167;151;150
          # Vitesses           300;300;300;300;300;300
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:45;09:47;09:51;09:52;09:53;09:55;10:02
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000006
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:30;106;PARI;SUP
          # Transfert          10:00:00;121.155
          # Secteurs_traverses AP;TE;RB
          # Heures_entree      09:45:14;09:47:46;09:55:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0202
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1835;A321;EDDT;LFPG;09:58:05;VCAG;MMOY;DEPOT
          # Identifiant        107
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EDDT;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:47:44;09:49:42;09:53:42;09:56:00;09:56:56;09:58:06
          # Niveaux            300;280;188;150;150;150
          # Vitesses           300;310;300;310;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:48;09:50;09:54;09:55;09:56;09:58;10:05
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000007
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:33;107;PARI;SUP
          # Transfert          10:00:00;121.155
          # Secteurs_traverses AP;TE;RB
          # Heures_entree      09:47:44;09:50:14;09:58:08
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0203
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     SAS559;A320;EKCH;LFPG;10:00:41;VCAG;MMOY;DEPOT
          # Identifiant        108
          <PLN_SUITE>          SAS;ETMOY;IFR;BASE;EKCH;1
          <NIVEAUX>            310;300;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:50:22;09:51:28;09:56:10;09:58:34;09:59:32;10:00:42
          # Niveaux            300;273;167;150;150;150
          # Vitesses           300;300;300;310;310;310
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:51;09:52;09:56;09:58;09:59;10:00;10:08
          # Niveaux_STIP       300;310;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000008
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:36;108;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00
          # Transfert          10:00:00;121.155
          # Secteurs_traverses AP;TE;RB
          # Heures_entree      09:50:22;09:51:34;10:00:44
          # Secteurs_traverses_STIP AP;TE;RB
          # TOD                 
          # Code_SSR           0701
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     KLM16P;B737;EHAM;LFPG;10:02:38;VCAG;MMOY;DEPOT
          # Identifiant        109
          <PLN_SUITE>          KLM;ETMOY;IFR;BASE;EHAM;1
          <NIVEAUX>            290;290;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:51:56;09:53:08;09:58:16;10:00:40;10:01:32;10:02:38
          # Niveaux            290;265;166;150;150;150
          # Vitesses           280;280;280;330;330;330
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:53;09:54;09:58;10:00;10:01;10:02;10:10
          # Niveaux_STIP       290;290;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000009
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:38;109;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00
          # Transfert          10:00:00;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      09:51:56;10:02:40
          # Secteurs_traverses_STIP AP;TE;RB
          # TOD                 
          # Code_SSR           0102
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     DLH06E;A319;EDDL;LFPG;10:04:38;VCAG;MMOY;DEPOT
          # Identifiant        110
          <PLN_SUITE>          DLH;ETMOY;IFR;BASE;EDDL;1
          <NIVEAUX>            230;230;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:54:00;09:55:10;10:00:10;10:02:32;10:03:28;10:04:38
          # Niveaux            230;230;150;150;150;150
          # Vitesses           310;310;310;310;310;310
          <FL_BALISES>         230;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      09:55;09:56;10:00;10:02;10:03;10:04;10:12
          # Niveaux_STIP       230;230;230;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000000A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:40;110;PARI;SUP
          <TRANSFERT_JOUE>     10:02:00
          # Transfert          10:00:00;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      09:54:00;10:04:40
          # Secteurs_traverses_STIP TE;RB
          # TOD                 
          # Code_SSR           2501
          <FREQ_ADJACENT>      128.100
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR345;B772;CYUL;LFPG;10:05:35;VCAG;MMOY;DEPOT
          # Identifiant        111
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;CYUL;1
          <NIVEAUX>            280;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           09:54:46;09:56:20;09:57:48;10:05:36;10:06:56
          # Niveaux            250;240;240;111;100
          # Vitesses           300;295;295;300;265
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:50;09:51;09:52;09:53;09:56;09:57;09:58;10:05;10:06;10:12
          # Niveaux_STIP       250;275;213;188;150;150;150;120;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000000B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:41;111;PARI;SUP
          <TRANSFERT_JOUE>     10:04:00
          # Transfert          10:01:50;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      09:54:46;10:06:58
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           0204
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AAL44;B789;KJFK;LFPG;10:07:35;VCAG;MMOY;DEPOT
          # Identifiant        112
          <PLN_SUITE>          AAL;ETMOY;IFR;BASE;KJFK;1
          <NIVEAUX>            280;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           09:57:26;09:58:54;10:00:16;10:07:36;10:08:54
          # Niveaux            250;240;240;116;100
          # Vitesses           314;320;320;314;298
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:52;09:53;09:54;09:56;09:58;09:59;10:00;10:07;10:08;10:17
          # Niveaux_STIP       250;266;277;185;150;150;150;118;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000000C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:43;112;PARI;SUP
          <TRANSFERT_JOUE>     10:06:00
          # Transfert          10:03:50;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      09:57:26;10:08:56
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           0205
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ICE540;B752;BIKF;LFPG;10:09:35;VCAG;MMOY;DEPOT
          # Identifiant        113
          <PLN_SUITE>          ICE;ETMOY;IFR;BASE;BIKF;1
          <NIVEAUX>            280;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           09:58:58;10:00:30;10:01:48;10:09:36;10:11:04
          # Niveaux            250;240;240;115;100
          # Vitesses           290;330;330;290;262
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:53;09:54;09:55;09:57;09:59;10:01;10:01;10:09;10:10;10:16
          # Niveaux_STIP       250;276;216;189;150;150;150;120;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000000D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:44;113;PARI;SUP
          <TRANSFERT_JOUE>     10:08:00
          # Transfert          10:06:00;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      09:58:58;10:11:06
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           0206
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1579;E170;EIDW;LFPG;10:15:35;VCAG;MMOY;DEPOT
          # Identifiant        114
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EIDW;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:04:24;10:05:58;10:07:24;10:15:36;10:17:10
          # Niveaux            250;240;240;100;100
          # Vitesses           300;300;300;250;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:59;10:00;10:01;10:03;10:05;10:07;10:07;10:15;10:17;10:23
          # Niveaux_STIP       250;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000000E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:50;114;PARI;SUP
          <TRANSFERT_JOUE>     10:14:00
          # Transfert          10:12:10;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:04:24;10:17:12
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2001
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR117;B772;ZSPD;LFPG;10:09:35;VCAG;MMOY;DEPOT
          # Identifiant        115
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;ZSPD;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           09:59:16;10:01:18;10:05:14;10:07:24;10:08:22;10:09:36
          # Niveaux            300;280;212;175;159;150
          # Vitesses           300;295;300;300;300;295
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:00;10:02;10:05;10:07;10:08;10:09;10:16
          # Niveaux_STIP       300;333;270;194;172;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000000F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:45;115;PARI;SUP
          <TRANSFERT_JOUE>     10:07:00
          # Transfert          10:04:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      09:59:16;10:09:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0207
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR111;A388;ZSPD;LFPG;10:11:35;VCAG;MMOY;DEPOT
          # Identifiant        116
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;ZSPD;1
          <NIVEAUX>            400;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:01:20;10:03:20;10:07:16;10:09:24;10:10:22;10:11:36
          # Niveaux            300;280;215;181;165;150
          # Vitesses           300;300;300;300;300;300
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:01;10:03;10:07;10:09;10:10;10:11;10:22
          # Niveaux_STIP       300;323;270;186;170;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000010
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:46;116;PARI;SUP
          <TRANSFERT_JOUE>     10:09:00
          # Transfert          10:06:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:01:20;10:11:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0210
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1319;A318;EDDF;LFPG;10:13:35;VCAG;MMOY;DEPOT
          # Identifiant        117
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EDDF;1
          <NIVEAUX>            220;220;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:02:42;10:04:52;10:09:14;10:11:30;10:12:26;10:13:36
          # Niveaux            220;220;150;150;150;150
          # Vitesses           310;310;310;310;310;310
          <FL_BALISES>         220;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:04;10:06;10:09;10:11;10:12;10:13;10:21
          # Niveaux_STIP       220;220;220;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000011
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:49;117;PARI;SUP
          <TRANSFERT_JOUE>     10:11:00
          # Transfert          10:08:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:02:42;10:13:38
          # Secteurs_traverses_STIP TE;RB
          # TOD                 
          # Code_SSR           0611
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     BAW314;A319;EGLL;LFPG;10:23:35;VCAG;MMOY;DEPOT
          # Identifiant        118
          <PLN_SUITE>          BAW;ETMOY;IFR;BASE;EGLL;1
          <NIVEAUX>            230;230;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:12:00;10:13:32;10:14:56;10:23:36;10:25:08
          # Niveaux            230;230;230;100;100
          # Vitesses           310;310;310;250;250
          <FL_BALISES>         230;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      10:07;10:08;10:09;10:11;10:13;10:15;10:15;10:23;10:25;10:31
          # Niveaux_STIP       230;230;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000012
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:58;118;PARI;SUP
          <TRANSFERT_JOUE>     10:22:00
          # Transfert          10:20:00;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:12:00;10:25:10
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2202
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     CPA261;A359;VHHH;LFPG;10:17:35;VCAG;MMOY;DEPOT
          # Identifiant        119
          <PLN_SUITE>          CPA;ETLON;IFR;BASE;VHHH;1
          <NIVEAUX>            350;300;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:07:30;10:08:36;10:13:10;10:15:34;10:16:30;10:17:36
          # Niveaux            300;279;195;152;150;150
          # Vitesses           300;300;300;300;330;330
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       SISGA;DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:06;10:08;10:09;10:13;10:15;10:16;10:17;10:28
          # Niveaux_STIP       300;260;260;260;186;170;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000013
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:53;119;PARI;SUP
          <TRANSFERT_JOUE>     10:15:00
          # Transfert          10:12:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:07:30;10:17:38
          # Secteurs_traverses_STIP NL;TE;RB
          # TOD                 
          # Code_SSR           2301
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EXS315;B733;EGNM;LFPG;10:27:35;VCAG;MMOY;DEPOT
          # Identifiant        120
          <PLN_SUITE>          EXS;ETMOY;IFR;BASE;EGNM;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:16:10;10:17:46;10:19:12;10:27:36;10:29:08
          # Niveaux            250;240;240;100;100
          # Vitesses           280;300;300;272;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      10:11;10:12;10:13;10:15;10:17;10:19;10:19;10:27;10:29;10:35
          # Niveaux_STIP       250;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000014
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:02;120;PARI;SUP
          <TRANSFERT_JOUE>     10:26:00
          # Transfert          10:24:00;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:16:10;10:29:10
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2203
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU79KP;A319;LKPR;LFPG;10:21:35;VCAG;MMOY;DEPOT
          # Identifiant        121
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LKPR;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:11:10;10:13:08;10:17:10;10:19:28;10:20:26;10:21:36
          # Niveaux            300;280;177;150;150;150
          # Vitesses           300;310;300;310;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:11;10:13;10:17;10:18;10:19;10:21;10:28
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000015
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:56;121;PARI;SUP
          <TRANSFERT_JOUE>     10:19:00
          # Transfert          10:16:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:11:10;10:21:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           6602
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1473;E170;EGPD;LFPG;10:31:35;VCAG;MMOY;DEPOT
          # Identifiant        122
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EGPD;1
          <NIVEAUX>            260;260;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:20:22;10:21:54;10:23:20;10:31:36;10:33:08
          # Niveaux            260;240;240;100;100
          # Vitesses           300;300;300;250;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      10:15;10:16;10:17;10:19;10:21;10:23;10:23;10:31;10:33;10:39
          # Niveaux_STIP       260;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000016
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:06;122;PARI;SUP
          <TRANSFERT_JOUE>     10:30:00
          # Transfert          10:28:00;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:20:22;10:33:10
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2204
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1019;A318;EDDF;LFPG;10:25:35;VCAG;MMOY;DEPOT
          # Identifiant        123
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EDDF;1
          <NIVEAUX>            220;220;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:14:42;10:16:52;10:21:14;10:23:30;10:24:26;10:25:36
          # Niveaux            220;220;150;150;150;150
          # Vitesses           310;310;310;310;310;310
          <FL_BALISES>         220;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:16;10:18;10:21;10:23;10:24;10:25;10:33
          # Niveaux_STIP       220;220;220;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000017
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:01;123;PARI;SUP
          <TRANSFERT_JOUE>     10:23:00
          # Transfert          10:20:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:14:42;10:25:38
          # Secteurs_traverses_STIP TE;RB
          # TOD                 
          # Code_SSR           0612
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR107;B772;ZGGG;LFPG;10:27:35;VCAG;MMOY;DEPOT
          # Identifiant        124
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;ZGGG;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:17:16;10:19:18;10:23:14;10:25:24;10:26:22;10:27:36
          # Niveaux            300;280;212;175;159;150
          # Vitesses           300;295;300;300;300;295
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:18;10:20;10:23;10:25;10:26;10:27;10:34
          # Niveaux_STIP       300;333;270;194;172;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000018
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:03;124;PARI;SUP
          <TRANSFERT_JOUE>     10:25:00
          # Transfert          10:22:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:17:16;10:27:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0211
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     DLH33K;A320;EDDM;LFPG;10:29:35;VCAG;MMOY;DEPOT
          # Identifiant        125
          <PLN_SUITE>          DLH;ETMOY;IFR;BASE;EDDM;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:19:14;10:21:12;10:25:10;10:27:28;10:28:26;10:29:36
          # Niveaux            300;280;194;150;150;150
          # Vitesses           300;310;300;308;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:19;10:21;10:25;10:26;10:27;10:29;10:36
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000019
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:04;125;PARI;SUP
          <TRANSFERT_JOUE>     10:27:00
          # Transfert          10:24:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:19:14;10:29:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0212
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1069;A320;EGCC;LFPG;10:39:35;VCAG;MMOY;DEPOT
          # Identifiant        126
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EGCC;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:28:34;10:30:06;10:31:28;10:39:36;10:41:10
          # Niveaux            250;240;240;100;100
          # Vitesses           300;310;310;250;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      10:23;10:24;10:25;10:27;10:29;10:31;10:31;10:39;10:41;10:47
          # Niveaux_STIP       250;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000001A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:14;126;PARI;SUP
          <TRANSFERT_JOUE>     10:38:00
          # Transfert          10:36:10;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:28:34;10:41:12
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2205
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     RJA117;A320;OJAI;LFPG;10:33:35;VCAG;MMOY;DEPOT
          # Identifiant        127
          <PLN_SUITE>          RJA;ETMOY;IFR;BASE;OJAI;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:23:14;10:25:12;10:29:10;10:31:28;10:32:26;10:33:36
          # Niveaux            300;280;194;150;150;150
          # Vitesses           300;310;300;308;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:23;10:25;10:29;10:30;10:31;10:33;10:40
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000001B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:08;127;PARI;SUP
          <TRANSFERT_JOUE>     10:31:00
          # Transfert          10:28:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:23:14;10:33:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           5701
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     QTR037;B77W;OTBD;LFPG;10:37:35;VCAG;MMOY;DEPOT
          # Identifiant        128
          <PLN_SUITE>          QTR;ETLON;IFR;BASE;OTBD;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:27:48;10:29:42;10:33:26;10:35:32;10:36:26;10:37:36
          # Niveaux            300;280;215;178;162;150
          # Vitesses           314;320;314;314;314;320
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:27;10:29;10:33;10:34;10:35;10:37;10:47
          # Niveaux_STIP       300;322;270;186;170;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000001C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:12;128;PARI;SUP
          <TRANSFERT_JOUE>     10:35:00
          # Transfert          10:32:30;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:27:48;10:37:38
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           5702
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1711;A318;EDDH;LFPG;10:35:17;VCAG;MMOY;DEPOT
          # Identifiant        129
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EDDH;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:24:54;10:26:00;10:30:50;10:33:12;10:34:08;10:35:18
          # Niveaux            300;269;150;150;150;150
          # Vitesses           300;300;306;310;310;310
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:26;10:27;10:31;10:33;10:34;10:35;10:43
          # Niveaux_STIP       300;321;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000001D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:11;129;PARI;SUP
          <TRANSFERT_JOUE>     10:34:00
          # Transfert          10:30:10;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:24:54;10:35:20
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0213
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FDX5029;B752;EDDM;LFPG;10:43:59;VCAG;MMOY;DEPOT
          # Identifiant        130
          <PLN_SUITE>          FDX;ETMOY;IFR;BASE;EDDM;1
          <NIVEAUX>            340;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:33:32;10:35:34;10:39:30;10:41:46;10:42:46;10:44:00
          # Niveaux            300;280;217;177;160;150
          # Vitesses           290;320;290;290;290;327
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:34;10:36;10:39;10:41;10:42;10:43;10:51
          # Niveaux_STIP       300;334;270;194;172;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000001E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:19;130;PARI;SUP
          <TRANSFERT_JOUE>     10:41:00
          # Transfert          10:39:00;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:33:32;10:44:02
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0214
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1425;E170;EDDW;LFPG;10:15:17;VCAG;MMOY;DEPOT
          # Identifiant        131
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EDDW;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:04:50;10:05:56;10:10:40;10:13:06;10:14:04;10:15:18
          # Niveaux            300;273;164;150;150;150
          # Vitesses           300;300;300;300;300;300
          <FL_BALISES>         260;150;;;;
          # Balises_STIP       DELOM;MOPIL;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:06;10:07;10:11;10:13;10:14;10:15;10:23
          # Niveaux_STIP       300;321;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000001F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:51;131;PARI;SUP
          <TRANSFERT_JOUE>     10:13:00
          # Transfert          10:10:10;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:04:50;10:15:20
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0215
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     BCS2582;B734;EGNX;LFPG;10:47:56;VCAG;MMOY;DEPOT
          # Identifiant        132
          <PLN_SUITE>          BCS;ETMOY;IFR;BASE;EGNX;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:36:58;10:38:32;10:39:58;10:47:56;10:49:30
          # Niveaux            250;240;240;100;100
          # Vitesses           300;300;300;250;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      10:31;10:32;10:33;10:35;10:37;10:39;10:39;10:47;10:49;10:55
          # Niveaux_STIP       250;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000020
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:22;132;PARI;SUP
          <TRANSFERT_JOUE>     10:47:00
          # Transfert          10:44:30;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:36:58;10:49:32
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2206
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AIC143;B788;VIDP;LFPG;10:50:11;VCAG;MMOY;DEPOT
          # Identifiant        133
          <PLN_SUITE>          AIC;ETLON;IFR;BASE;VIDP;1
          <NIVEAUX>            400;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:40:24;10:42:18;10:46:02;10:48:08;10:49:02;10:50:12
          # Niveaux            300;280;215;178;162;150
          # Vitesses           314;320;314;314;314;320
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:41;10:43;10:46;10:48;10:49;10:50;11:01
          # Niveaux_STIP       300;322;270;186;170;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000021
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:26;133;PARI;SUP
          <TRANSFERT_JOUE>     10:48:00
          # Transfert          10:45:10;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:40:24;10:50:14
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           2302
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1411;A321;EDDH;LFPG;10:52:50;VCAG;MMOY;DEPOT
          # Identifiant        134
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EDDH;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:42:28;10:44:26;10:48:26;10:50:44;10:51:40;10:52:50
          # Niveaux            300;280;188;150;150;150
          # Vitesses           300;310;300;310;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:42;10:44;10:48;10:49;10:50;10:52;10:59
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000022
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:27;134;PARI;SUP
          <TRANSFERT_JOUE>     10:50:00
          # Transfert          10:47:50;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:42:28;10:52:52
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0216
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     GWI7406;A319;EDDH;LFPG;10:55:11;VCAG;MMOY;DEPOT
          # Identifiant        135
          <PLN_SUITE>          GWI;ETMOY;IFR;BASE;EDDH;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:44:46;10:46:44;10:50:46;10:53:04;10:54:02;10:55:12
          # Niveaux            300;280;177;150;150;150
          # Vitesses           300;310;300;310;310;310
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:45;10:47;10:51;10:52;10:53;10:55;11:02
          # Niveaux_STIP       300;336;270;194;173;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000023
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:30;135;PARI;SUP
          <TRANSFERT_JOUE>     10:53:00
          # Transfert          10:50:10;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:44:46;10:55:14
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           0217
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     BAW306;A319;EGLL;LFPG;10:11:50;VCAG;MMOY;DEPOT
          # Identifiant        136
          <PLN_SUITE>          BAW;ETMOY;IFR;BASE;EGLL;1
          <NIVEAUX>            230;230;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:00:14;10:01:46;10:03:10;10:11:50;10:13:22
          # Niveaux            230;230;230;100;100
          # Vitesses           310;310;310;250;250
          <FL_BALISES>         230;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:55;09:56;09:57;09:59;10:01;10:03;10:03;10:11;10:13;10:19
          # Niveaux_STIP       230;230;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000024
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:46;136;PARI;SUP
          <TRANSFERT_JOUE>     10:09:00
          # Transfert          10:08:20;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:00:14;10:13:24
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2207
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     HVN11;A359;VVTS;LFPG;10:46:05;VCAG;MMOY;DEPOT
          # Identifiant        137
          <PLN_SUITE>          HVN;ETLON;IFR;BASE;VVTS;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      RAPOR
          <ARRIVEE_TERRAIN>    LOR09L_RJ;09;L;
          <CALAGE_BALISE>      LORNI
          <BALISES>            RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI
          # Estimees           10:35:58;10:37:56;10:41:44;10:43:56;10:44:54;10:46:06
          # Niveaux            300;280;218;179;162;150
          # Vitesses           300;329;300;300;300;329
          <FL_BALISES>         280;150;;;;
          # Balises_STIP       RAPOR;VEDUS;XERAM;ENORI;DEVIM;LORNI;PGNE
          # Estimees_STIP      10:37;10:39;10:42;10:44;10:45;10:46;10:57
          # Niveaux_STIP       300;322;270;186;170;150;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000025
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:22;137;PARI;SUP
          <TRANSFERT_JOUE>     10:44:00
          # Transfert          10:41:00;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:35:58;10:46:08
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB
          # TOD                 
          # Code_SSR           2303
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1059;E170;EGNT;LFPG;10:13:35;VCAG;MMOY;DEPOT
          # Identifiant        138
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EGNT;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:02:24;10:03:58;10:05:24;10:13:36;10:15:10
          # Niveaux            250;240;240;100;100
          # Vitesses           300;300;300;250;250
          <FL_BALISES>         240;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      09:57;09:58;09:59;10:01;10:03;10:05;10:05;10:13;10:15;10:21
          # Niveaux_STIP       250;247;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000026
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:48;138;PARI;SUP
          <TRANSFERT_JOUE>     10:11:00
          # Transfert          10:10:10;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:02:24;10:15:12
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2210
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1481;A319;EGLL;LFPG;10:43:35;VCAG;MMOY;DEPOT
          # Identifiant        139
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;EGLL;1
          <NIVEAUX>            230;230;
          <DEPART_BALISE>      XIDIL
          <ARRIVEE_TERRAIN>    M0P09L_RJ;09;L;
          <CALAGE_BALISE>      KOLIV
          <BALISES>            XIDIL;PETAX;BIBAX;KOLIV;M0PAR
          # Estimees           10:32:00;10:33:32;10:34:56;10:43:36;10:45:08
          # Niveaux            230;230;230;100;100
          # Vitesses           310;310;310;250;250
          <FL_BALISES>         230;;100;;
          # Balises_STIP       SFD;WAFFU;HARDY;XIDIL;PETAX;BIBAX;BIBA;KOLIV;MOPAR;PGNWR
          # Estimees_STIP      10:27;10:28;10:29;10:31;10:33;10:35;10:35;10:43;10:45;10:51
          # Niveaux_STIP       230;230;218;190;150;150;150;121;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000027
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:18;139;PARI;SUP
          <TRANSFERT_JOUE>     10:42:00
          # Transfert          10:40:00;121.155
          # Secteurs_traverses TP;RB
          # Heures_entree      10:32:00;10:45:10
          # Secteurs_traverses_STIP GF;TP;RB
          # TOD                 
          # Code_SSR           2211
          # Frequence_Initiale_Adjacent       128.875
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1417;E170;LIMJ;LFPG;09:42:55;VCAG;MMOY;DEPOT
          # Identifiant        140
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LIMJ;1
          <NIVEAUX>            340;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_R;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:29:44;09:37:18;09:41:38;09:42:56
          # Niveaux            300;200;150;150
          # Vitesses           300;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:31;09:31;09:36;09:38;09:41;09:42;09:51
          # Niveaux_STIP       300;309;340;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000028
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:16;140;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;118.150
          # Transfert          
          # Secteurs_traverses 
          # Heures_entree      
          # Secteurs_traverses_STIP UJ;AR;US;AR;RA
          # TOD                 
          # Code_SSR           5703
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR511M;E170;LSZH;LFPG;09:47:01;VCAG;MMOY;DEPOT
          # Identifiant        141
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LSZH;1
          <NIVEAUX>            310;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_R;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:33:50;09:41:24;09:45:44;09:47:02
          # Niveaux            300;200;150;150
          # Vitesses           300;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       LASUN;MOROK;PENDU;GIVRI;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:22;09:26;09:30;09:33;09:36;09:37;09:42;09:43;09:46;09:47;09:56
          # Niveaux_STIP       230;240;310;310;310;280;280;280;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000029
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:18;141;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;118.150
          # Transfert          
          # Secteurs_traverses 
          # Heures_entree      
          # Secteurs_traverses_STIP ZW;UH;UJ;AR;RA
          # TOD                 
          # Code_SSR           3001
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU47MC;A319;GMMN;LFPG;09:50:35;VCAG;MMOY;DEPOT
          # Identifiant        142
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;GMMN;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_R;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:33:30;09:39:14;09:40:42;09:45:24;09:49:14;09:50:36
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:33;09:36;09:39;09:40;09:46;09:49;09:50;09:59
          # Niveaux_STIP       300;349;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000002A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:18;142;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;118.150
          # Transfert          
          # Secteurs_traverses 
          # Heures_entree      
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           1001
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ENT475;B738;LFRS;LFPG;09:57:14;VCAG;MMOY;DEPOT
          # Identifiant        143
          <PLN_SUITE>          ENT;ETMOY;IFR;BASE;LFRS;1
          <NIVEAUX>            220;220;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_R;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:40:52;09:45:44;09:47:06;09:52:02;09:55:58;09:57:14
          # Niveaux            220;220;220;150;110;110
          # Vitesses           330;330;330;317;330;330
          <FL_BALISES>         220;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:41;09:45;09:47;09:52;09:56;09:57;10:06
          # Niveaux_STIP       220;220;220;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000002B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:26;143;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;118.150
          # Transfert          10:00:00;125.830
          # Secteurs_traverses OY;OG;RT;RA
          # Heures_entree      09:40:52;09:41:26;09:48:38;09:57:16
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           0220
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR77YS;E170;LFRN;LFPG;09:59:14;VCAG;MMOY;DEPOT
          # Identifiant        144
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFRN;1
          <NIVEAUX>            220;220;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_R;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:42:18;09:47:42;09:49:08;09:53:58;09:57:50;09:59:14
          # Niveaux            220;220;220;150;110;110
          # Vitesses           300;300;300;300;300;300
          <FL_BALISES>         220;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:43;09:47;09:49;09:54;09:58;09:59;10:08
          # Niveaux_STIP       220;220;220;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000002C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:28;144;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;118.150
          # Transfert          10:00:00;125.830
          # Secteurs_traverses OY;OG;RT;RA
          # Heures_entree      09:42:18;09:42:56;09:50:04;09:59:16
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           0221
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     SWR60W;BCS1;LSZH;LFPG;09:52:13;VCAG;MMOY;DEPOT
          # Identifiant        145
          <PLN_SUITE>          SWR;ETMOY;IFR;BASE;LSZH;1
          <NIVEAUX>            310;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_R;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:38:34;09:46:24;09:50:52;09:52:14
          # Niveaux            300;200;150;150
          # Vitesses           290;290;290;290
          <FL_BALISES>         200;150;;
          # Balises_STIP       LASUN;MOROK;PENDU;GIVRI;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:25;09:30;09:33;09:37;09:40;09:40;09:46;09:47;09:50;09:52;10:01
          # Niveaux_STIP       230;240;310;310;310;280;270;251;201;187;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000002D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:22;145;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00
          # Transfert          10:00:00;125.830
          # Secteurs_traverses UJ;AR;RA
          # Heures_entree      09:38:34;09:38:54;09:52:16
          # Secteurs_traverses_STIP ZW;UH;UJ;AR;RA
          # TOD                 
          # Code_SSR           3002
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU78FX;A319;LIMC;LFPG;09:56:55;VCAG;MMOY;DEPOT
          # Identifiant        146
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LIMC;1
          <NIVEAUX>            340;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:43:54;09:51:24;09:55:40;09:56:56
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:45;09:45;09:50;09:52;09:55;09:56;10:05
          # Niveaux_STIP       300;309;340;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000002E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:30;146;PARI;SUP
          # Transfert          10:00:00;125.830
          # Secteurs_traverses UJ;AR;RA
          # Heures_entree      09:43:54;09:44:12;09:56:58
          # Secteurs_traverses_STIP UJ;AR;US;AR;RA
          # TOD                 
          # Code_SSR           5704
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     SVA143;B773;OERK;LFPG;09:58:55;VCAG;MMOY;DEPOT
          # Identifiant        147
          <PLN_SUITE>          SVA;ETLON;IFR;BASE;OERK;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:46:30;09:53:36;09:57:42;09:58:56
          # Niveaux            300;200;150;150
          # Vitesses           314;320;320;320
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:48;09:48;09:53;09:54;09:57;09:58;10:06
          # Niveaux_STIP       300;308;360;277;202;175;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000002F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:33;147;PARI;SUP
          # Transfert          10:00:00;125.830
          # Secteurs_traverses UJ;AR;RA
          # Heures_entree      09:46:30;09:46:48;09:58:58
          # Secteurs_traverses_STIP UJ;AR;KD;AR;US;AR;RA
          # TOD                 
          # Code_SSR           5705
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1001;A319;LEMD;LFPG;10:08:05;VCAG;MMOY;DEPOT
          # Identifiant        148
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LEMD;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:51:00;09:56:44;09:58:12;10:02:54;10:06:44;10:08:06
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:51;09:54;09:57;09:58;10:04;10:07;10:08;10:17
          # Niveaux_STIP       300;349;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000030
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:36;148;PARI;SUP
          <TRANSFERT_JOUE>     10:06:00
          # Transfert          10:03:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      09:51:00;09:59:50;10:08:08
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           1002
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FPO748;B733;LFMT;LFPG;10:02:01;VCAG;MMOY;DEPOT
          # Identifiant        149
          <PLN_SUITE>          FPO;ETMOY;IFR;BASE;LFMT;1
          <NIVEAUX>            300;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:48:20;09:56:12;10:00:42;10:02:02
          # Niveaux            300;200;150;150
          # Vitesses           275;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:51;09:51;09:56;09:58;10:01;10:02;10:10
          # Niveaux_STIP       300;300;300;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000031
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:36;149;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00
          # Transfert          10:00:00;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      09:48:20;10:02:04
          # Secteurs_traverses_STIP UJ;AR;US;AR;RA
          # TOD                 
          # Code_SSR           3502
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FDX5053;B752;LFSB;LFPG;10:04:55;VCAG;MMOY;DEPOT
          # Identifiant        150
          <PLN_SUITE>          FDX;ETMOY;IFR;BASE;LFSB;1
          <NIVEAUX>            280;280;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:51:54;09:59:26;10:03:42;10:04:56
          # Niveaux            280;200;150;150
          # Vitesses           290;330;330;330
          <FL_BALISES>         200;150;;
          # Balises_STIP       LSB;LSBS1;SB600;SB618;MOROK;MEDIM;PENDU;GIVRI;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:37;09:37;09:38;09:41;09:43;09:44;09:46;09:50;09:53;09:53;09:58;09:59;10:03;10:04;10:12
          # Niveaux_STIP       0;17;140;150;150;230;230;280;280;280;280;280;206;182;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000032
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:35;150;PARI;SUP
          <TRANSFERT_JOUE>     10:02:00
          # Transfert          10:00:00;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      09:51:54;10:04:58
          # Secteurs_traverses_STIP BA;SE;UH;UJ;AR;RA
          # TOD                 
          # Code_SSR           0222
          <FREQ_ADJACENT>      132.100
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     THY1DF;A321;LTFM;LFPG;10:06:55;VCAG;MMOY;DEPOT
          # Identifiant        151
          <PLN_SUITE>          THY;ETMOY;IFR;BASE;LTFM;1
          <NIVEAUX>            320;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:53:54;10:01:22;10:05:38;10:06:56
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:55;09:55;10:00;10:02;10:05;10:06;10:15
          # Niveaux_STIP       300;309;320;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000033
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:40;151;PARI;SUP
          <TRANSFERT_JOUE>     10:04:00
          # Transfert          10:01:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      09:53:54;10:06:58
          # Secteurs_traverses_STIP UJ;AR;US;AR;RA
          # TOD                 
          # Code_SSR           4101
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR109B;E170;LEVX;LFPG;10:16:05;VCAG;MMOY;DEPOT
          # Identifiant        152
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LEVX;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:59:38;10:04:40;10:06:08;10:10:50;10:14:42;10:16:06
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;300;300;300;300;300
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:00;10:04;10:06;10:11;10:15;10:16;10:25
          # Niveaux_STIP       300;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000034
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:45;152;PARI;SUP
          <TRANSFERT_JOUE>     10:14:00
          # Transfert          10:11:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      09:59:38;10:07:48;10:16:08
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           5501
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FDX5051;B752;LFSB;LFPG;10:10:58;VCAG;MMOY;DEPOT
          # Identifiant        153
          <PLN_SUITE>          FDX;ETMOY;IFR;BASE;LFSB;1
          <NIVEAUX>            280;280;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:57:56;10:05:28;10:09:44;10:10:58
          # Niveaux            280;200;150;150
          # Vitesses           290;330;330;330
          <FL_BALISES>         200;150;;
          # Balises_STIP       LSB;LSBS1;SB600;SB618;MOROK;MEDIM;PENDU;GIVRI;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:43;09:43;09:44;09:47;09:49;09:50;09:52;09:56;09:59;09:59;10:04;10:05;10:09;10:10;10:18
          # Niveaux_STIP       0;17;140;150;150;230;230;280;280;280;280;280;206;182;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000035
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:41;153;PARI;SUP
          <TRANSFERT_JOUE>     10:08:00
          # Transfert          10:05:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      09:57:56;10:11:00
          # Secteurs_traverses_STIP BA;SE;UH;UJ;AR;RA
          # TOD                 
          # Code_SSR           0223
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR37EW;E190;LFRB;LFPG;10:19:02;VCAG;MMOY;DEPOT
          # Identifiant        154
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFRB;1
          <NIVEAUX>            300;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:01:56;10:07:40;10:09:08;10:13:50;10:17:40;10:19:02
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       LFRB;TEL1;ROSPO;DEGEX;KORER;GODAN;KURIS;ANG;T300;TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:38;09:41;09:45;09:49;09:53;09:56;09:58;10:01;10:02;10:03;10:08;10:09;10:15;10:18;10:19;10:28
          # Niveaux_STIP       0;120;190;258;300;300;300;300;300;300;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000036
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:48;154;PARI;SUP
          <TRANSFERT_JOUE>     10:17:00
          # Transfert          10:14:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:01:56;10:10:46;10:19:04
          # Secteurs_traverses_STIP GP;IX;KS;NS;OG;RT;RA
          # TOD                 
          # Code_SSR           0224
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1049;A318;LEBL;LFPG;10:22:05;VCAG;MMOY;DEPOT
          # Identifiant        155
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LEBL;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:05:00;10:10:44;10:12:12;10:16:54;10:20:44;10:22:06
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:05;10:08;10:11;10:12;10:18;10:21;10:22;10:31
          # Niveaux_STIP       300;349;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000037
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:50;155;PARI;SUP
          <TRANSFERT_JOUE>     10:20:00
          # Transfert          10:17:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:05:00;10:13:50;10:22:08
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           5502
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AEA1007;B738;LEVC;LFPG;10:24:05;VCAG;MMOY;DEPOT
          # Identifiant        156
          <PLN_SUITE>          AEA;ETMOY;IFR;BASE;LEVC;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:06:48;10:12:40;10:14:00;10:18:48;10:22:48;10:24:06
          # Niveaux            300;240;240;160;110;110
          # Vitesses           280;330;330;280;330;330
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:07;10:10;10:13;10:14;10:20;10:23;10:24;10:33
          # Niveaux_STIP       300;349;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000038
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:52;156;PARI;SUP
          <TRANSFERT_JOUE>     10:22:00
          # Transfert          10:19:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:06:48;10:15:42;10:24:08
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           5503
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ETH704;B788;HAAB;LFPG;10:18:20;VCAG;MMOY;DEPOT
          # Identifiant        157
          <PLN_SUITE>          ETH;ETLON;IFR;BASE;HAAB;1
          <NIVEAUX>            300;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:05:54;10:13:00;10:17:06;10:18:20
          # Niveaux            300;200;150;150
          # Vitesses           314;320;320;320
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:06;10:06;10:11;10:13;10:17;10:18;10:29
          # Niveaux_STIP       300;300;212;186;117;96;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000039
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:51;157;PARI;SUP
          <TRANSFERT_JOUE>     10:16:00
          # Transfert          10:13:20;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:05:54;10:18:22
          # Secteurs_traverses_STIP UJ;AR;RA
          # TOD                 
          # Code_SSR           5706
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     MEA211;A332;OLBA;LFPG;10:20:46;VCAG;MMOY;DEPOT
          # Identifiant        158
          <PLN_SUITE>          MEA;ETLON;IFR;BASE;OLBA;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:07:40;10:15:10;10:19:28;10:20:46
          # Niveaux            300;200;150;150
          # Vitesses           300;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:09;10:09;10:14;10:16;10:19;10:20;10:29
          # Niveaux_STIP       300;309;380;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000003A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:54;158;PARI;SUP
          <TRANSFERT_JOUE>     10:18:00
          # Transfert          10:15:40;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:07:40;10:20:48
          # Secteurs_traverses_STIP UJ;AR;KD;US;AR;RA
          # TOD                 
          # Code_SSR           5707
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR95JZ;A319;LFBO;LFPG;10:30:05;VCAG;MMOY;DEPOT
          # Identifiant        159
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFBO;1
          <NIVEAUX>            340;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:13:00;10:18:44;10:20:12;10:24:54;10:28:44;10:30:06
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:13;10:16;10:19;10:20;10:25;10:29;10:30;10:39
          # Niveaux_STIP       300;340;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000003B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:58;159;PARI;SUP
          <TRANSFERT_JOUE>     10:28:00
          # Transfert          10:25:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:13:00;10:21:50;10:30:08
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           0225
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FDX5233;B763;LIMC;LFPG;10:24:55;VCAG;MMOY;DEPOT
          # Identifiant        160
          <PLN_SUITE>          FDX;ETLON;IFR;BASE;LIMC;1
          <NIVEAUX>            320;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:11:56;10:19:26;10:23:44;10:24:56
          # Niveaux            300;200;150;150
          # Vitesses           290;330;330;330
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:14;10:14;10:19;10:20;10:23;10:24;10:32
          # Niveaux_STIP       300;308;320;282;206;180;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000003C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:59;160;PARI;SUP
          <TRANSFERT_JOUE>     10:22:00
          # Transfert          10:19:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:11:56;10:24:58
          # Secteurs_traverses_STIP UJ;AR;RA
          # TOD                 
          # Code_SSR           5710
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU32LT;A319;LPPT;LFPG;10:34:05;VCAG;MMOY;DEPOT
          # Identifiant        161
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LPPT;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:17:50;10:22:48;10:24:12;10:28:54;10:32:44;10:34:06
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:18;10:22;10:24;10:29;10:33;10:34;10:43
          # Niveaux_STIP       300;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000003D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:03;161;PARI;SUP
          <TRANSFERT_JOUE>     10:32:00
          # Transfert          10:29:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:17:50;10:25:50;10:34:08
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           2304
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU88HK;A319;LICC;LFPG;10:28:55;VCAG;MMOY;DEPOT
          # Identifiant        162
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LICC;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:15:54;10:23:24;10:27:40;10:28:56
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:17;10:17;10:22;10:24;10:27;10:28;10:37
          # Niveaux_STIP       300;309;380;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000003E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:02;162;PARI;SUP
          <TRANSFERT_JOUE>     10:26:00
          # Transfert          10:23:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:15:54;10:28:58
          # Secteurs_traverses_STIP UJ;AR;KD;US;AR;RA
          # TOD                 
          # Code_SSR           5711
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1229;E170;LIPE;LFPG;10:30:55;VCAG;MMOY;DEPOT
          # Identifiant        163
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LIPE;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:17:44;10:25:18;10:29:38;10:30:56
          # Niveaux            300;200;150;150
          # Vitesses           300;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:19;10:19;10:24;10:26;10:29;10:30;10:39
          # Niveaux_STIP       300;309;360;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000003F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:04;163;PARI;SUP
          <TRANSFERT_JOUE>     10:28:00
          # Transfert          10:25:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:17:44;10:30:58
          # Secteurs_traverses_STIP UJ;AR;KD;US;AR;RA
          # TOD                 
          # Code_SSR           5712
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FHY546;A320;LFRS;LFPG;10:40:05;VCAG;MMOY;DEPOT
          # Identifiant        164
          <PLN_SUITE>          BIF;ETMOY;IFR;BASE;LFRS;1
          <NIVEAUX>            220;220;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:23:32;10:28:44;10:30:08;10:34:56;10:38:44;10:40:06
          # Niveaux            220;220;220;150;110;110
          # Vitesses           310;310;310;310;310;310
          <FL_BALISES>         220;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:24;10:28;10:30;10:35;10:39;10:40;10:49
          # Niveaux_STIP       220;220;220;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000040
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:09;164;PARI;SUP
          <TRANSFERT_JOUE>     10:38:00
          # Transfert          10:35:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:23:32;10:31:08;10:40:08
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           0226
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1401;A321;LEMD;LFPG;10:42:05;VCAG;MMOY;DEPOT
          # Identifiant        165
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LEMD;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:25:02;10:30:46;10:32:14;10:36:54;10:40:44;10:42:06
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:25;10:28;10:31;10:32;10:38;10:41;10:42;10:51
          # Niveaux_STIP       300;349;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000041
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:10;165;PARI;SUP
          <TRANSFERT_JOUE>     10:40:00
          # Transfert          10:37:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:25:02;10:33:54;10:42:08
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           1003
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     SWR61D;BCS1;LSZH;LFPG;10:33:58;VCAG;MMOY;DEPOT
          # Identifiant        166
          <PLN_SUITE>          SWR;ETMOY;IFR;BASE;LSZH;1
          <NIVEAUX>            290;290;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:20:14;10:28:08;10:32:36;10:33:58
          # Niveaux            290;200;150;150
          # Vitesses           290;290;290;290
          <FL_BALISES>         200;150;;
          # Balises_STIP       LASUN;MOROK;PENDU;GIVRI;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:06;10:11;10:14;10:18;10:21;10:21;10:27;10:28;10:31;10:33;10:42
          # Niveaux_STIP       230;240;290;290;290;280;270;251;201;187;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000042
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:03;166;PARI;SUP
          <TRANSFERT_JOUE>     10:31:00
          # Transfert          10:28:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:20:14;10:34:00
          # Secteurs_traverses_STIP ZW;UH;UJ;AR;RA
          # TOD                 
          # Code_SSR           3003
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1077;E190;LEBB;LFPG;10:46:02;VCAG;MMOY;DEPOT
          # Identifiant        167
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LEBB;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:28:56;10:34:40;10:36:08;10:40:50;10:44:40;10:46:02
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:29;10:32;10:35;10:36;10:42;10:45;10:46;10:55
          # Niveaux_STIP       300;349;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000043
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:14;167;PARI;SUP
          <TRANSFERT_JOUE>     10:44:00
          # Transfert          10:41:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:28:56;10:37:46;10:46:04
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           5504
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR681;B772;KATL;LFPG;10:47:59;VCAG;MMOY;DEPOT
          # Identifiant        168
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;KATL;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:30:46;10:36:36;10:38:08;10:42:46;10:46:34;10:48:00
          # Niveaux            300;240;240;162;110;110
          # Vitesses           300;295;295;300;295;295
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:31;10:34;10:36;10:37;10:43;10:46;10:47;10:55
          # Niveaux_STIP       300;346;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000044
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:16;168;PARI;SUP
          <TRANSFERT_JOUE>     10:45:00
          # Transfert          10:43:00;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:30:46;10:39:48;10:48:02
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           0227
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1543;A318;LSGG;LFPG;10:42:31;VCAG;MMOY;DEPOT
          # Identifiant        169
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LSGG;1
          <NIVEAUX>            260;260;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:29:22;10:37:00;10:41:16;10:42:32
          # Niveaux            260;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       LGG;KELUK;DJL;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:19;10:22;10:28;10:31;10:31;10:36;10:38;10:41;10:42;10:50
          # Niveaux_STIP       260;260;260;260;260;260;260;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000045
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:13;169;PARI;SUP
          <TRANSFERT_JOUE>     10:40:00
          # Transfert          10:37:30;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:29:22;10:42:34
          # Secteurs_traverses_STIP 1L;UJ;AR;RA
          # TOD                 
          # Code_SSR           5713
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR86VC;A318;LFMT;LFPG;10:47:07;VCAG;MMOY;DEPOT
          # Identifiant        170
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFMT;1
          <NIVEAUX>            340;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:34:06;10:41:36;10:45:52;10:47:08
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:36;10:36;10:41;10:43;10:46;10:47;10:56
          # Niveaux_STIP       300;309;340;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000046
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:21;170;PARI;SUP
          <TRANSFERT_JOUE>     10:45:00
          # Transfert          10:42:00;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:34:06;10:47:10
          # Secteurs_traverses_STIP UJ;AR;US;AR;RA
          # TOD                 
          # Code_SSR           3503
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1205;A319;LIRF;LFPG;10:49:49;VCAG;MMOY;DEPOT
          # Identifiant        171
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LIRF;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:36:48;10:44:18;10:48:34;10:49:50
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:38;10:38;10:43;10:45;10:48;10:49;10:58
          # Niveaux_STIP       300;309;380;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000047
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:23;171;PARI;SUP
          <TRANSFERT_JOUE>     10:47:00
          # Transfert          10:44:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:36:48;10:49:52
          # Secteurs_traverses_STIP UJ;AR;KD;US;AR;RA
          # TOD                 
          # Code_SSR           4001
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     LZB431;E190;LBSF;LFPG;10:51:49;VCAG;MMOY;DEPOT
          # Identifiant        172
          <PLN_SUITE>          LZB;ETMOY;IFR;BASE;LBSF;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:38:48;10:46:18;10:50:34;10:51:50
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:40;10:40;10:45;10:47;10:50;10:51;11:00
          # Niveaux_STIP       300;309;380;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000048
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:25;172;PARI;SUP
          <TRANSFERT_JOUE>     10:49:00
          # Transfert          10:46:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:38:48;10:51:52
          # Secteurs_traverses_STIP UJ;AR;KD;US;AR;RA
          # TOD                 
          # Code_SSR           2701
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU3760;A319;LPPT;LFPG;10:10:10;VCAG;MMOY;DEPOT
          # Identifiant        173
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LPPT;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:53:54;09:58:52;10:00:16;10:04:58;10:08:48;10:10:10
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:54;09:59;10:00;10:05;10:09;10:10;10:19
          # Niveaux_STIP       300;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000049
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:39;173;PARI;SUP
          <TRANSFERT_JOUE>     10:08:00
          # Transfert          10:05:10;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      09:53:54;10:01:54;10:10:12
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           2305
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR31PX;A318;LFRS;LFPG;10:12:10;VCAG;MMOY;DEPOT
          # Identifiant        174
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFRS;1
          <NIVEAUX>            240;240;
          <DEPART_BALISE>      TEMTO
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           09:55:52;10:00:54;10:02:16;10:06:58;10:10:48;10:12:10
          # Niveaux            240;240;240;150;110;110
          # Vitesses           310;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       TEMTO;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      09:56;10:00;10:02;10:07;10:11;10:12;10:21
          # Niveaux_STIP       240;240;240;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000004A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:41;174;PARI;SUP
          <TRANSFERT_JOUE>     10:10:00
          # Transfert          10:07:10;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      09:55:52;10:03:54;10:12:12
          # Secteurs_traverses_STIP OG;RT;RA
          # TOD                 
          # Code_SSR           0230
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ENT801;B738;LFLL;LFPG;10:15:37;VCAG;MMOY;DEPOT
          # Identifiant        175
          <PLN_SUITE>          ENT;ETMOY;IFR;BASE;LFLL;1
          <NIVEAUX>            220;220;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:02:38;10:10:02;10:14:26;10:15:38
          # Niveaux            220;200;150;150
          # Vitesses           280;330;330;330
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:04;10:04;10:09;10:10;10:14;10:15;10:23
          # Niveaux_STIP       220;220;220;220;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000004B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:49;175;PARI;SUP
          <TRANSFERT_JOUE>     10:14:00
          # Transfert          10:10:30;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:02:38;10:15:40
          # Secteurs_traverses_STIP UJ;AR;RA
          # TOD                 
          # Code_SSR           0231
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR75RT;E190;LFBP;LFPG;10:26:20;VCAG;MMOY;DEPOT
          # Identifiant        176
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFBP;1
          <NIVEAUX>            340;300;
          <DEPART_BALISE>      PEPAX
          <ARRIVEE_TERRAIN>    BAN08R_RJ;08;R;
          <CALAGE_BALISE>      BANOX
          <BALISES>            PEPAX;KEPER;LUMAN;ROMGO;NERKI;BANOX
          # Estimees           10:09:14;10:14:58;10:16:26;10:21:08;10:24:58;10:26:20
          # Niveaux            300;240;240;150;110;110
          # Vitesses           300;310;310;310;310;310
          <FL_BALISES>         240;;150;110;;
          # Balises_STIP       PEPAX;NIMER;KEPER;LUMAN;ROMGO;NERKI;BANOX;PGSW
          # Estimees_STIP      10:09;10:12;10:15;10:16;10:21;10:25;10:26;10:35
          # Niveaux_STIP       300;340;280;260;160;160;140;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000004C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:54;176;PARI;SUP
          <TRANSFERT_JOUE>     10:24:00
          # Transfert          10:21:20;125.830
          # Secteurs_traverses OG;RT;RA
          # Heures_entree      10:09:14;10:18:04;10:26:22
          # Secteurs_traverses_STIP OG;XS;OG;RT;RA
          # TOD                 
          # Code_SSR           0232
          # Frequence_Initiale_Adjacent       122.575
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR833;A332;FCPP;LFPG;10:08:58;VCAG;MMOY;DEPOT
          # Identifiant        177
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;FCPP;1
          <NIVEAUX>            380;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:55:52;10:03:22;10:07:40;10:08:58
          # Niveaux            300;200;150;150
          # Vitesses           300;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      09:57;09:57;10:02;10:04;10:07;10:08;10:17
          # Niveaux_STIP       300;309;380;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000004D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:42;177;PARI;SUP
          <TRANSFERT_JOUE>     10:07:00
          # Transfert          10:03:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      09:55:52;10:09:00
          # Secteurs_traverses_STIP UJ;AR;KD;US;AR;RA
          # TOD                 
          # Code_SSR           0233
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1551;A332;LFML;LFPG;10:13:00;VCAG;MMOY;DEPOT
          # Identifiant        178
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;LFML;1
          <NIVEAUX>            320;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           09:59:54;10:07:24;10:11:42;10:13:00
          # Niveaux            300;200;150;150
          # Vitesses           300;300;300;300
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:02;10:02;10:07;10:09;10:12;10:13;10:22
          # Niveaux_STIP       300;309;320;292;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000004E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:47;178;PARI;SUP
          <TRANSFERT_JOUE>     10:11:00
          # Transfert          10:08:00;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      09:59:54;10:13:02
          # Secteurs_traverses_STIP UJ;AR;US;AR;RA
          # TOD                 
          # Code_SSR           2212
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1215;E190;LSZH;LFPG;10:40:34;VCAG;MMOY;DEPOT
          # Identifiant        179
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LSZH;1
          <NIVEAUX>            310;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:27:32;10:35:02;10:39:18;10:40:34
          # Niveaux            300;200;150;150
          # Vitesses           300;310;310;310
          <FL_BALISES>         200;150;;
          # Balises_STIP       LASUN;MOROK;PENDU;GIVRI;TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:15;10:19;10:23;10:26;10:29;10:30;10:35;10:36;10:39;10:40;10:49
          # Niveaux_STIP       230;240;310;310;310;280;280;280;210;186;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000004F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:11;179;PARI;SUP
          <TRANSFERT_JOUE>     10:38:00
          # Transfert          10:35:30;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:27:32;10:40:36
          # Secteurs_traverses_STIP ZW;UH;UJ;AR;RA
          # TOD                 
          # Code_SSR           3004
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ELY323;B789;LLBG;LFPG;10:36:55;VCAG;MMOY;DEPOT
          # Identifiant        180
          <PLN_SUITE>          ELY;ETLON;IFR;BASE;LLBG;1
          <NIVEAUX>            360;300;
          <DEPART_BALISE>      TINIL
          <ARRIVEE_TERRAIN>    OKIS08R_RJ;08;R;
          <CALAGE_BALISE>      OKIPA
          <BALISES>            TINIL;NANOP;URELO;OKIPA
          # Estimees           10:24:30;10:31:36;10:35:42;10:36:56
          # Niveaux            300;200;150;150
          # Vitesses           314;320;320;320
          <FL_BALISES>         200;150;;
          # Balises_STIP       TINIL;UJAR;ERTIP;NANOP;URELO;OKIPA;PGSE
          # Estimees_STIP      10:24;10:24;10:29;10:31;10:35;10:36;10:48
          # Niveaux_STIP       300;305;357;186;117;96;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000050
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:09;180;PARI;SUP
          <TRANSFERT_JOUE>     10:34:00
          # Transfert          10:31:50;125.830
          # Secteurs_traverses AR;RA
          # Heures_entree      10:24:30;10:36:58
          # Secteurs_traverses_STIP UJ;AR;KD;AR;US;AR;RA
          # TOD                 
          # Code_SSR           5714
          # Frequence_Initiale_Adjacent       132.100
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR786Y;E190;LFPG;EGBB;09:59:00;VCAG;MMOY;DEPOT
          # Identifiant        181
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            260;A4;100
          <DEPART_TERRAIN>     OPALE5G_R;09;R
          <ARRIVEE_BALISE>     ALESO
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OPALE;KESAX;DIMAL;ALESO
          # Estimees           10:13:08;10:15:38;10:19:46;10:20:48
          # Niveaux            100;168;220;220
          # Vitesses           310;300;310;310
          <FL_BALISES>         220;;;
          # Balises_STIP       LPG;EDG;PG092;OPALE;KESAX;DIMAL;ALESO
          # Estimees_STIP      09:59;10:00;10:00;10:11;10:13;10:16;10:17
          # Niveaux_STIP       0;22;23;140;260;260;260
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000051
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:54;181;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00
          # Transfert          10:00:00;124.355
          # Secteurs_traverses RD;TL;TN
          # Heures_entree      09:59:00;10:02:30;10:03:44
          # Secteurs_traverses_STIP RD;TN;GY
          # TOD                 
          # Code_SSR           0234
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EIN521;A320;LFPG;EIDW;10:09:12;VCAG;MMOY;DEPOT
          # Identifiant        182
          <PLN_SUITE>          EIN;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            360;A4;100
          <DEPART_TERRAIN>     ATREX5G_R;09;R
          <ARRIVEE_BALISE>     SOVAT
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ATREX;VESAN;RATUK;SOVAT
          # Estimees           10:20:34;10:26:46;10:29:52;10:31:12
          # Niveaux            100;245;260;260
          # Vitesses           310;300;310;310
          <FL_BALISES>         260;;;
          # Balises_STIP       LPG;EDG;PG092;ATREX;VESAN;RATUK;SOVAT
          # Estimees_STIP      10:09;10:10;10:10;10:19;10:24;10:27;10:28
          # Niveaux_STIP       0;22;23;140;310;360;360
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000052
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:04;182;PARI;SUP
          <TRANSFERT_JOUE>     10:10:00
          # Transfert          10:09:42;124.355
          # Secteurs_traverses RD;TL;TB;TN
          # Heures_entree      10:09:12;10:12:34;10:13:36;10:14:08
          # Secteurs_traverses_STIP RD;TN;UN;KN;GL
          # TOD                 
          # Code_SSR           0235
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AUA412G;A321;LFPG;LOWW;10:01:54;VCAG;MMOY;DEPOT
          # Identifiant        183
          <PLN_SUITE>          AUA;ETLON;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     RANUX5G_R;09;R
          <ARRIVEE_BALISE>     VALEK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            RANUX;MEDOX;VALEK
          # Estimees           10:16:08;10:21:02;10:25:06
          # Niveaux            100;217;260
          # Vitesses           310;300;310
          <FL_BALISES>         260;;
          # Balises_STIP       LPG;EDG;PG092;PG094;NEPAR;RANUX;MEDOX;VALEK
          # Estimees_STIP      10:01;10:02;10:02;10:03;10:08;10:12;10:17;10:20
          # Niveaux_STIP       0;22;23;55;140;270;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000053
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:56;183;PARI;SUP
          <TRANSFERT_JOUE>     10:03:00
          # Transfert          10:02:24;124.355
          # Secteurs_traverses RD;TL;TM
          # Heures_entree      10:01:54;10:05:18;10:08:22
          # Secteurs_traverses_STIP RD;TM;XR
          # TOD                 
          # Code_SSR           0236
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     THA931;A359;LFPG;VTBS;10:03:54;VCAG;MMOY;DEPOT
          # Identifiant        184
          <PLN_SUITE>          THA;ETLON;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     RANUX5G_R;09;R
          <ARRIVEE_BALISE>     VALEK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            RANUX;MEDOX;VALEK
          # Estimees           10:18:08;10:23:06;10:27:18
          # Niveaux            100;199;259
          # Vitesses           330;300;300
          <FL_BALISES>         260;;
          # Balises_STIP       LPG;EDG;PG092;PG094;NEPAR;RANUX;MEDOX;VALEK
          # Estimees_STIP      10:03;10:04;10:04;10:06;10:12;10:16;10:20;10:23
          # Niveaux_STIP       0;23;24;56;140;270;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000054
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:58;184;PARI;SUP
          <TRANSFERT_JOUE>     10:05:00
          # Transfert          10:04:24;124.355
          # Secteurs_traverses RD;TL;TM
          # Heures_entree      10:03:54;10:08:24;10:10:48
          # Secteurs_traverses_STIP RD;TM;XR
          # TOD                 
          # Code_SSR           0237
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     CSN348A;A332;LFPG;ZGGG;10:05:54;VCAG;MMOY;DEPOT
          # Identifiant        185
          <PLN_SUITE>          CSN;ETLON;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     RANUX5G_R;09;R
          <ARRIVEE_BALISE>     VALEK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            RANUX;MEDOX;VALEK
          # Estimees           10:20:42;10:25:42;10:29:54
          # Niveaux            100;200;260
          # Vitesses           300;300;300
          <FL_BALISES>         260;;
          # Balises_STIP       LPG;EDG;PG092;PG094;NEPAR;RANUX;MEDOX;VALEK
          # Estimees_STIP      10:05;10:06;10:06;10:07;10:12;10:16;10:21;10:24
          # Niveaux_STIP       0;22;23;55;140;270;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000055
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:00;185;PARI;SUP
          <TRANSFERT_JOUE>     10:07:00
          # Transfert          10:06:24;124.355
          # Secteurs_traverses RD;TL;TM
          # Heures_entree      10:05:54;10:10:06;10:12:42
          # Secteurs_traverses_STIP RD;TM;XR
          # TOD                 
          # Code_SSR           0240
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR46WL;E170;LFPG;EGCC;10:08:00;VCAG;MMOY;DEPOT
          # Identifiant        186
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            260;A4;100
          <DEPART_TERRAIN>     ATREX5G_R;09;R
          <ARRIVEE_BALISE>     SOVAT
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ATREX;VESAN;RATUK;SOVAT
          # Estimees           10:19:42;10:25:50;10:29:00;10:30:22
          # Niveaux            100;253;260;260
          # Vitesses           300;300;300;300
          <FL_BALISES>         260;;;
          # Balises_STIP       LPG;EDG;PG092;ATREX;VESAN;RATUK;SOVAT
          # Estimees_STIP      10:08;10:09;10:09;10:18;10:22;10:25;10:27
          # Niveaux_STIP       0;22;23;140;260;260;260
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000056
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:03;186;PARI;SUP
          <TRANSFERT_JOUE>     10:09:00
          # Transfert          10:08:30;124.355
          # Secteurs_traverses RD;TL;TB;TN
          # Heures_entree      10:08:00;10:11:28;10:12:30;10:13:02
          # Secteurs_traverses_STIP RD;TN;GR
          # TOD                 
          # Code_SSR           0241
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     WOW405;A321;LFPG;BIKF;10:10:00;VCAG;MMOY;DEPOT
          # Identifiant        187
          <PLN_SUITE>          BIF;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            260;A4;100
          <DEPART_TERRAIN>     ATREX5G_R;09;R
          <ARRIVEE_BALISE>     SOVAT
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ATREX;VESAN;RATUK;SOVAT
          # Estimees           10:21:20;10:27:32;10:30:40;10:31:58
          # Niveaux            100;241;260;260
          # Vitesses           310;300;310;310
          <FL_BALISES>         260;;;
          # Balises_STIP       LPG;EDG;PG092;ATREX;VESAN;RATUK;SOVAT
          # Estimees_STIP      10:10;10:11;10:11;10:20;10:24;10:27;10:29
          # Niveaux_STIP       0;22;23;140;260;260;260
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000057
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:05;187;PARI;SUP
          <TRANSFERT_JOUE>     10:11:00
          # Transfert          10:10:30;124.355
          # Secteurs_traverses RD;TL;TB;TN
          # Heures_entree      10:10:00;10:13:24;10:14:20;10:14:52
          # Secteurs_traverses_STIP RD;TN;GR
          # TOD                 
          # Code_SSR           0242
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1618;A318;LFPG;EDDF;10:14:24;VCAG;MMOY;DEPOT
          # Identifiant        188
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            230;A4;100
          <DEPART_TERRAIN>     RANUX5G_R;09;R
          <ARRIVEE_BALISE>     VALEK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            RANUX;MEDOX;VALEK
          # Estimees           10:28:46;10:33:38;10:37:44
          # Niveaux            100;228;230
          # Vitesses           310;300;310
          <FL_BALISES>         230;;
          # Balises_STIP       LPG;EDG;PG092;PG094;NEPAR;RANUX;MEDOX;VALEK
          # Estimees_STIP      10:14;10:15;10:15;10:16;10:21;10:25;10:29;10:33
          # Niveaux_STIP       0;22;23;55;140;230;230;230
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000058
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:09;188;PARI;SUP
          <TRANSFERT_JOUE>     10:15:00
          # Transfert          10:14:54;124.355
          # Secteurs_traverses RD;TL;TM
          # Heures_entree      10:14:24;10:17:54;10:21:00
          # Secteurs_traverses_STIP RD;TM
          # TOD                 
          # Code_SSR           0243
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1978;E170;LFPG;EIDW;10:19:00;VCAG;MMOY;DEPOT
          # Identifiant        189
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            260;A4;100
          <DEPART_TERRAIN>     ATREX5G_R;09;R
          <ARRIVEE_BALISE>     SOVAT
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ATREX;VESAN;RATUK;SOVAT
          # Estimees           10:30:42;10:36:50;10:40:00;10:41:22
          # Niveaux            100;253;260;260
          # Vitesses           300;300;300;300
          <FL_BALISES>         260;;;
          # Balises_STIP       LPG;EDG;PG092;ATREX;VESAN;RATUK;SOVAT
          # Estimees_STIP      10:19;10:20;10:20;10:29;10:33;10:36;10:38
          # Niveaux_STIP       0;22;23;140;260;260;260
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000059
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:14;189;PARI;SUP
          <TRANSFERT_JOUE>     10:20:00
          # Transfert          10:19:30;124.355
          # Secteurs_traverses RD;TL;TB;TN
          # Heures_entree      10:19:00;10:22:28;10:23:30;10:24:02
          # Secteurs_traverses_STIP RD;TN;GR
          # TOD                 
          # Code_SSR           0244
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1286;E170;LFPG;EGPH;10:27:48;VCAG;MMOY;DEPOT
          # Identifiant        190
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            260;A4;100
          <DEPART_TERRAIN>     ATREX5G_R;09;R
          <ARRIVEE_BALISE>     SOVAT
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ATREX;VESAN;RATUK;SOVAT
          # Estimees           10:39:30;10:45:38;10:48:48;10:50:10
          # Niveaux            100;253;260;260
          # Vitesses           300;300;300;300
          <FL_BALISES>         260;;;
          # Balises_STIP       LPG;EDG;PG092;ATREX;VESAN;RATUK;SOVAT
          # Estimees_STIP      10:27;10:28;10:28;10:37;10:41;10:44;10:46
          # Niveaux_STIP       0;22;23;140;260;260;260
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000005A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:22;190;PARI;SUP
          <TRANSFERT_JOUE>     10:29:00
          # Transfert          10:28:18;124.355
          # Secteurs_traverses RD;TL;TB;TN
          # Heures_entree      10:27:48;10:31:16;10:32:18;10:32:50
          # Secteurs_traverses_STIP RD;TN;GR
          # TOD                 
          # Code_SSR           0245
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ABR2CL;AT43;LFPG;EGNT;10:23:18;VCAG;MMOY;DEPOT
          # Identifiant        191
          <PLN_SUITE>          ABR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            180;A4;A50
          <DEPART_TERRAIN>     OPALE5G_H;09;R
          <ARRIVEE_BALISE>     ALESO
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OPALE;KESAX;DIMAL;ALESO
          # Estimees           10:47:08;10:51:32;10:59:38;11:01:36
          # Niveaux            57;116;180;180
          # Vitesses           177;160;172;172
          <FL_BALISES>         180;;;
          # Balises_STIP       LPG;EDG;PG092;OPALE;KESAX;DIMAL;ALESO
          # Estimees_STIP      10:23;10:24;10:24;10:41;10:44;10:51;10:52
          # Niveaux_STIP       0;26;28;140;180;180;180
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000005B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:18;191;PARI;SUP
          <TRANSFERT_JOUE>     10:24:00
          # Transfert          10:23:48;124.355
          # Secteurs_traverses RD;TN
          # Heures_entree      10:23:18;10:36:08
          # Secteurs_traverses_STIP RD;TN;GY
          # TOD                 
          # Code_SSR           0246
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EDC893;C25B;LFPG;EGGW;10:36:15;VCAG;MMOY;DEPOT
          # Identifiant        192
          <PLN_SUITE>          BIF;ETCOU;IFR;BASE;LFPG;1
          <NIVEAUX>            240;A4;100
          <DEPART_TERRAIN>     OPALE5G_R;09;R
          <ARRIVEE_BALISE>     ALESO
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OPALE;KESAX;DIMAL;ALESO
          # Estimees           10:51:26;10:54:26;10:59:24;11:00:34
          # Niveaux            100;175;220;220
          # Vitesses           280;230;280;280
          <FL_BALISES>         220;;;
          # Balises_STIP       LPG;EDG;PG092;OPALE;KESAX;DIMAL;ALESO
          # Estimees_STIP      10:36;10:37;10:37;10:50;10:52;10:56;10:57
          # Niveaux_STIP       0;26;27;140;240;240;240
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000005C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:31;192;PARI;SUP
          <TRANSFERT_JOUE>     10:37:00
          # Transfert          10:36:46;124.355
          # Secteurs_traverses RD;TL;TN
          # Heures_entree      10:36:16;10:39:30;10:40:52
          # Secteurs_traverses_STIP RD;TN;GY
          # TOD                 
          # Code_SSR           0247
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1134;A320;LFPG;EDDT;10:31:51;VCAG;MMOY;DEPOT
          # Identifiant        193
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            350;A4;100
          <DEPART_TERRAIN>     RANUX5G_R;09;R
          <ARRIVEE_BALISE>     VALEK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            RANUX;MEDOX;VALEK
          # Estimees           10:46:08;10:51:00;10:55:04
          # Niveaux            100;219;260
          # Vitesses           310;300;310
          <FL_BALISES>         260;;
          # Balises_STIP       LPG;EDG;PG092;PG094;NEPAR;RANUX;MEDOX;VALEK
          # Estimees_STIP      10:31;10:32;10:32;10:33;10:38;10:42;10:47;10:50
          # Niveaux_STIP       0;22;23;55;140;270;350;350
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000005D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:26;193;PARI;SUP
          <TRANSFERT_JOUE>     10:33:00
          # Transfert          10:32:22;124.355
          # Secteurs_traverses RD;TL;TM
          # Heures_entree      10:31:52;10:35:14;10:38:20
          # Secteurs_traverses_STIP RD;TM;XR;KR
          # TOD                 
          # Code_SSR           0250
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AAL755;A333;LFPG;KPHL;10:41:00;VCAG;MMOY;DEPOT
          # Identifiant        194
          <PLN_SUITE>          AAL;ETLON;IFR;BASE;LFPG;1
          <NIVEAUX>            260;A4;100
          <DEPART_TERRAIN>     ATREX5G_R;09;R
          <ARRIVEE_BALISE>     SOVAT
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ATREX;VESAN;RATUK;SOVAT
          # Estimees           10:52:24;10:58:44;11:01:58;11:03:14
          # Niveaux            100;220;260;260
          # Vitesses           330;300;308;330
          <FL_BALISES>         260;;;
          # Balises_STIP       LPG;EDG;PG092;ATREX;VESAN;RATUK;SOVAT
          # Estimees_STIP      10:41;10:42;10:42;10:51;10:55;10:58;11:00
          # Niveaux_STIP       0;22;23;140;260;260;260
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000005E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:36;194;PARI;SUP
          <TRANSFERT_JOUE>     10:42:00
          # Transfert          10:41:30;124.355
          # Secteurs_traverses RD;TN
          # Heures_entree      10:41:00;10:45:54
          # Secteurs_traverses_STIP RD;TN;GR
          # TOD                 
          # Code_SSR           0251
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR621U;A320;LFPG;ESSA;10:45:48;VCAG;MMOY;DEPOT
          # Identifiant        195
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            370;A4;100
          <DEPART_TERRAIN>     NURMO5G_R;09;R
          <ARRIVEE_BALISE>     ADUTO
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            NURMO;CMB;VEKIN;ADUTO
          # Estimees           10:56:48;11:01:36;11:03:18;11:04:20
          # Niveaux            100;218;251;268
          # Vitesses           310;300;300;300
          <FL_BALISES>         300;;;
          # Balises_STIP       LPG;EDG;PG092;NURMO;PERON;SULEX;CMB;CMB2;VEKIN;ADUTO
          # Estimees_STIP      10:45;10:46;10:46;10:55;10:56;10:57;10:59;11:00;11:01;11:02
          # Niveaux_STIP       0;22;23;190;272;286;321;336;345;361
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000005F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:40;195;PARI;SUP
          <TRANSFERT_JOUE>     10:46:00
          # Transfert          10:46:18;124.355
          # Secteurs_traverses RD;TL;TB
          # Heures_entree      10:45:48;10:49:10;10:49:50
          # Secteurs_traverses_STIP RD;TB;UB;YB;YU
          # TOD                 
          # Code_SSR           0252
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1084;A319;LFPG;DTTA;09:59:00;VCAG;MMOY;DEPOT
          # Identifiant        196
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            380;A4;120
          <DEPART_TERRAIN>     LATRA5H_R;08;L
          <ARRIVEE_BALISE>     LERGA
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LATRA;LAMUT;LAKOB;LERGA
          # Estimees           10:14:36;10:24:38;10:26:48;10:41:40
          # Niveaux            120;210;210;210
          # Vitesses           280;310;310;310
          <FL_BALISES>         210;;;
          # Balises_STIP       LPG;EDG;PG089;PG102;AELDG;LALUX;LATRA;LAMUT;LAKOB;KUKO1;UTUVA;LERGA
          # Estimees_STIP      09:59;10:00;10:02;10:06;10:12;10:12;10:13;10:21;10:23;10:26;10:31;10:36
          # Niveaux_STIP       0;22;68;158;200;270;270;290;290;290;380;380
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000060
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:54;196;PARI;SUP
          <TRANSFERT_JOUE>     10:00:00;133.380
          # Transfert          10:00:00;124.355
          # Secteurs_traverses RD;TL;DG;DO;DS;DO;P1;T1
          # Heures_entree      09:59:00;10:02:30;10:06:24;10:10:54;10:14:18;10:16:22;10:23:04;10:30:00
          # Secteurs_traverses_STIP RC;DG;P1;P4;T4
          # TOD                 
          # Code_SSR           0253
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AZA319;A321;LFPG;LIRF;10:03:00;VCAG;MMOY;DEPOT
          # Identifiant        197
          <PLN_SUITE>          AZA;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            350;A4;120
          <DEPART_TERRAIN>     OKASI5H_R;08;L
          <ARRIVEE_BALISE>     MOU
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees           10:17:22;10:23:42;10:27:12;10:28:18;10:31:04
          # Niveaux            120;254;260;260;260
          # Vitesses           280;300;310;310;310
          <FL_BALISES>         260;;;;
          # Balises_STIP       LPG;EDG;PG089;ODEDG;ODEBU;OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees_STIP      10:03;10:04;10:06;10:14;10:15;10:16;10:21;10:24;10:25;10:28
          # Niveaux_STIP       0;22;68;200;260;260;350;350;350;350
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000061
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:58;197;PARI;SUP
          <TRANSFERT_JOUE>     10:04:00;133.380
          # Transfert          10:03:30;124.355
          # Secteurs_traverses RD;TL;DG;DO;DS;DO;UP
          # Heures_entree      10:03:00;10:06:24;10:09:42;10:15:14;10:17:00;10:19:18;10:25:06
          # Secteurs_traverses_STIP RC;DG;PW
          # TOD                 
          # Code_SSR           0254
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ELY320;B772;LFPG;LLBG;10:05:00;VCAG;MMOY;DEPOT
          # Identifiant        198
          <PLN_SUITE>          ELY;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     LANVI5H_R;08;L
          <ARRIVEE_BALISE>     EPL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LANVI;EPL
          # Estimees           10:34:32;10:36:36
          # Niveaux            100;136
          # Vitesses           255;315
          <FL_BALISES>         330;
          # Balises_STIP       LPG;EDG;PG082;PG088;RD01R;LUPAM;LASIV;UFKF1;LANVI;EPL
          # Estimees_STIP      10:05;10:06;10:06;10:07;10:09;10:12;10:16;10:22;10:25;10:26
          # Niveaux_STIP       0;21;31;57;87;140;260;330;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000062
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:00;198;PARI;SUP
          <TRANSFERT_JOUE>     10:06:00;131.200
          # Transfert          10:05:30;124.355
          # Secteurs_traverses RD;TL;TL
          # Heures_entree      10:05:00;10:08:50;10:33:44
          # Secteurs_traverses_STIP RC;TL;UF;XE
          # TOD                 
          # Code_SSR           0255
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     THY5BL;A333;LFPG;LTFM;10:07:00;VCAG;MMOY;DEPOT
          # Identifiant        199
          <PLN_SUITE>          THY;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     LANVI5H_R;08;L
          <ARRIVEE_BALISE>     EPL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LANVI;EPL
          # Estimees           10:31:10;10:33:28
          # Niveaux            100;150
          # Vitesses           330;300
          <FL_BALISES>         330;
          # Balises_STIP       LPG;EDG;PG082;PG088;RD01R;LUPAM;LASIV;UFKF1;LANVI;EPL
          # Estimees_STIP      10:07;10:08;10:08;10:10;10:11;10:15;10:18;10:25;10:28;10:29
          # Niveaux_STIP       0;22;33;61;91;140;260;330;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000063
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:02;199;PARI;SUP
          <TRANSFERT_JOUE>     10:08:00;131.200
          # Transfert          10:07:30;124.355
          # Secteurs_traverses RD;TL;TL
          # Heures_entree      10:07:00;10:11:30;10:30:52
          # Secteurs_traverses_STIP RC;TL;UF;XE
          # TOD                 
          # Code_SSR           0256
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU3747;A319;LFPG;GMMN;10:09:00;VCAG;MMOY;DEPOT
          # Identifiant        200
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            370;A4;100
          <DEPART_TERRAIN>     LGL5H_R;08;L
          <ARRIVEE_BALISE>     DIDAK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LGL;GODIX;DIDAK
          # Estimees           10:31:30;10:36:50;10:38:18
          # Niveaux            100;240;269
          # Vitesses           310;300;300
          <FL_BALISES>         320;;
          # Balises_STIP       LPG;EDG;PG082;PG088;PG101;KELUD;THUZL;LGL;GODIX;DIDAK
          # Estimees_STIP      10:09;10:10;10:10;10:12;10:15;10:16;10:24;10:28;10:33;10:35
          # Niveaux_STIP       0;22;33;61;122;150;150;290;340;370
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000064
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:04;200;PARI;SUP
          <TRANSFERT_JOUE>     10:09:00;133.380
          # Transfert          10:09:30;124.355
          # Secteurs_traverses RD;TL;DG;TH;UK
          # Heures_entree      10:09:00;10:12:30;10:17:30;10:33:30;10:37:30
          # Secteurs_traverses_STIP RC;TH;UZ;XS;XI;NI
          # TOD                 
          # Code_SSR           0257
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AZA317;A320;LFPG;LIRF;10:11:00;VCAG;MMOY;DEPOT
          # Identifiant        201
          <PLN_SUITE>          AZA;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            380;A4;120
          <DEPART_TERRAIN>     OKASI5H_R;08;L
          <ARRIVEE_BALISE>     MOU
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees           10:25:24;10:31:42;10:35:12;10:36:18;10:39:04
          # Niveaux            120;258;260;260;260
          # Vitesses           280;300;310;310;310
          <FL_BALISES>         260;;;;
          # Balises_STIP       LPG;EDG;PG089;ODEDG;ODEBU;OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees_STIP      10:11;10:12;10:14;10:22;10:23;10:24;10:29;10:32;10:33;10:36
          # Niveaux_STIP       0;22;68;200;260;260;380;380;380;380
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000065
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:06;201;PARI;SUP
          <TRANSFERT_JOUE>     10:12:00;133.380
          # Transfert          10:11:30;124.355
          # Secteurs_traverses RD;TL;DG;DO;DS;DO;UP
          # Heures_entree      10:11:00;10:14:22;10:17:46;10:23:18;10:25:02;10:27:18;10:33:06
          # Secteurs_traverses_STIP RC;DG;PW;HP
          # TOD                 
          # Code_SSR           0260
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     DLH37Y;A320;LFPG;EDDM;10:13:00;VCAG;MMOY;DEPOT
          # Identifiant        202
          <PLN_SUITE>          DLH;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     LANVI5H_R;08;L
          <ARRIVEE_BALISE>     EPL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LANVI;EPL
          # Estimees           10:37:56;10:40:08
          # Niveaux            100;157
          # Vitesses           310;300
          <FL_BALISES>         330;
          # Balises_STIP       LPG;EDG;PG082;PG088;RD01R;LUPAM;LASIV;UFKF1;LANVI;EPL
          # Estimees_STIP      10:13;10:14;10:14;10:16;10:17;10:21;10:24;10:31;10:34;10:35
          # Niveaux_STIP       0;22;33;61;91;140;260;330;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000066
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:08;202;PARI;SUP
          <TRANSFERT_JOUE>     10:14:00;131.200
          # Transfert          10:13:30;124.355
          # Secteurs_traverses RD;TL;TL;E
          # Heures_entree      10:13:00;10:16:22;10:37:30;10:40:02
          # Secteurs_traverses_STIP RC;TL;UF;XE
          # TOD                 
          # Code_SSR           0261
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     SIA335;A359;LFPG;WSSS;10:15:00;VCAG;MMOY;DEPOT
          # Identifiant        203
          <PLN_SUITE>          SIA;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     LANVI5H_R;08;L
          <ARRIVEE_BALISE>     EPL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LANVI;EPL
          # Estimees           10:39:10;10:41:28
          # Niveaux            100;150
          # Vitesses           330;300
          <FL_BALISES>         330;
          # Balises_STIP       LPG;EDG;PG082;PG088;RD01R;LUPAM;LASIV;UFKF1;LANVI;EPL
          # Estimees_STIP      10:15;10:16;10:17;10:18;10:20;10:23;10:26;10:33;10:35;10:37
          # Niveaux_STIP       0;23;34;65;90;140;260;330;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000067
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:10;203;PARI;SUP
          <TRANSFERT_JOUE>     10:16:00;131.200
          # Transfert          10:15:30;124.355
          # Secteurs_traverses RD;TL;TL
          # Heures_entree      10:15:00;10:19:30;10:38:52
          # Secteurs_traverses_STIP RC;TL;UF;XE
          # TOD                 
          # Code_SSR           0262
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1532;A320;LFPG;LGAV;10:17:00;VCAG;MMOY;DEPOT
          # Identifiant        204
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            330;A4;100
          <DEPART_TERRAIN>     LANVI5H_R;08;L
          <ARRIVEE_BALISE>     EPL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LANVI;EPL
          # Estimees           10:41:56;10:44:08
          # Niveaux            100;157
          # Vitesses           310;300
          <FL_BALISES>         330;
          # Balises_STIP       LPG;EDG;PG082;PG088;RD01R;LUPAM;LASIV;UFKF1;LANVI;EPL
          # Estimees_STIP      10:17;10:18;10:18;10:20;10:21;10:25;10:28;10:35;10:38;10:39
          # Niveaux_STIP       0;22;33;61;91;140;260;330;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000068
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:12;204;PARI;SUP
          <TRANSFERT_JOUE>     10:18:00;131.200
          # Transfert          10:17:30;124.355
          # Secteurs_traverses RD;TL;TL;E
          # Heures_entree      10:17:00;10:20:22;10:41:30;10:44:02
          # Secteurs_traverses_STIP RC;TL;UF;XE
          # TOD                 
          # Code_SSR           0263
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR688;B772;LFPG;KATL;10:26:54;VCAG;MMOY;DEPOT
          # Identifiant        205
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;LFPG;1
          <NIVEAUX>            340;A4;100
          <DEPART_TERRAIN>     LGL5H_R;08;L
          <ARRIVEE_BALISE>     DIDAK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LGL;GODIX;DIDAK
          # Estimees           10:52:44;10:58:06;10:59:32
          # Niveaux            100;209;235
          # Vitesses           255;315;315
          <FL_BALISES>         320;;
          # Balises_STIP       LPG;EDG;PG082;PG088;PG101;KELUD;THUZL;LGL;GODIX;DIDAK
          # Estimees_STIP      10:26;10:27;10:27;10:28;10:31;10:33;10:40;10:44;10:48;10:50
          # Niveaux_STIP       0;21;31;57;116;146;150;290;340;340
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000069
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:21;205;PARI;SUP
          <TRANSFERT_JOUE>     10:28:00;133.380
          # Transfert          10:27:24;124.355
          # Secteurs_traverses RD;TL;DG;DG;TH
          # Heures_entree      10:26:54;10:30:44;10:35:42;10:42:30;10:55:32
          # Secteurs_traverses_STIP RC;TH;UZ;XS;NF
          # TOD                 
          # Code_SSR           0264
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR460;B77W;LFPG;FIMP;10:31:42;VCAG;MMOY;DEPOT
          # Identifiant        206
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;LFPG;1
          <NIVEAUX>            310;A4;120
          <DEPART_TERRAIN>     LATRA5H_R;08;L
          <ARRIVEE_BALISE>     LERGA
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LATRA;LAMUT;LAKOB;LERGA
          # Estimees           10:46:54;10:56:42;10:58:48;11:13:12
          # Niveaux            120;210;210;210
          # Vitesses           280;320;320;320
          <FL_BALISES>         210;;;
          # Balises_STIP       LPG;EDG;PG089;PG102;AELDG;LALUX;LATRA;LAMUT;LAKOB;KUKO1;UTUVA;LERGA
          # Estimees_STIP      10:31;10:32;10:35;10:39;10:44;10:43;10:45;10:52;10:54;10:57;11:02;11:07
          # Niveaux_STIP       0;23;73;146;200;270;270;290;290;290;310;310
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000006A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:26;206;PARI;SUP
          <TRANSFERT_JOUE>     10:32:00;133.380
          # Transfert          10:32:12;124.355
          # Secteurs_traverses RD;TL;DG;DO;DS;DO;P1;T1
          # Heures_entree      10:31:42;10:34:58;10:38:46;10:43:12;10:46:38;10:48:52;10:55:12;11:01:54
          # Secteurs_traverses_STIP RC;DG;P1;P2;T2
          # TOD                 
          # Code_SSR           0265
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1812;A319;LFPG;LIML;10:37:36;VCAG;MMOY;DEPOT
          # Identifiant        207
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            350;A4;100
          <DEPART_TERRAIN>     LANVI5H_R;08;L
          <ARRIVEE_BALISE>     EPL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LANVI;EPL
          # Estimees           11:02:40;11:04:52
          # Niveaux            100;160
          # Vitesses           310;300
          <FL_BALISES>         330;
          # Balises_STIP       LPG;EDG;PG082;PG088;RD01R;LUPAM;LASIV;UFKF1;LANVI;EPL
          # Estimees_STIP      10:37;10:38;10:38;10:40;10:41;10:45;10:48;10:55;10:58;10:59
          # Niveaux_STIP       0;22;33;61;91;140;260;340;350;350
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000006B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:32;207;PARI;SUP
          <TRANSFERT_JOUE>     10:39:00;131.200
          # Transfert          10:38:06;124.355
          # Secteurs_traverses RD;TL;TL;E
          # Heures_entree      10:37:36;10:41:06;11:02:14;11:04:40
          # Secteurs_traverses_STIP RC;TL;UF;KF;KE
          # TOD                 
          # Code_SSR           0266
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR12MJ;A320;LFPG;LFMN;10:44:27;VCAG;MMOY;DEPOT
          # Identifiant        208
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPG;1
          <NIVEAUX>            370;A4;120
          <DEPART_TERRAIN>     LATRA5H_R;08;L
          <ARRIVEE_BALISE>     LERGA
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LATRA;LAMUT;LAKOB;LERGA
          # Estimees           10:59:54;11:09:58;11:12:10;11:27:00
          # Niveaux            120;210;210;210
          # Vitesses           280;310;310;310
          <FL_BALISES>         210;;;
          # Balises_STIP       LPG;EDG;PG089;PG102;AELDG;LALUX;LATRA;LAMUT;LAKOB;KUKO1;UTUVA;LERGA
          # Estimees_STIP      10:44;10:45;10:47;10:51;10:57;10:57;10:58;11:06;11:08;11:11;11:16;11:21
          # Niveaux_STIP       0;22;68;158;200;270;270;290;290;290;370;370
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000006C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:39;208;PARI;SUP
          <TRANSFERT_JOUE>     10:45:00;133.380
          # Transfert          10:44:58;124.355
          # Secteurs_traverses RD;TL;DG;DO;DS;DO;P1;T1
          # Heures_entree      10:44:28;10:47:50;10:51:44;10:56:12;10:59:38;11:01:48;11:08:26;11:15:20
          # Secteurs_traverses_STIP RC;DG;P1;P4;T4
          # TOD                 
          # Code_SSR           0267
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     TVF232M;B738;LFPO;LIRN;10:42:42;VCAG;MMOY;DEPOT
          # Identifiant        209
          <PLN_SUITE>          BIF;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            370;A3;
          <DEPART_TERRAIN>     OKASI9E_R;07;N
          <ARRIVEE_BALISE>     MOU
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees           10:52:26;10:58:52;11:02:18;11:03:22;11:06:08
          # Niveaux            130;230;230;230;230
          # Vitesses           280;330;330;330;330
          <FL_BALISES>         230;;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;ODEBU;OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees_STIP      10:42;10:43;10:43;10:44;10:48;10:50;10:55;10:58;10:59;11:02
          # Niveaux_STIP       0;25;25;55;210;260;370;370;370;370
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000006D
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:37;209;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;UP
          # Heures_entree      10:42:42;10:45:30;10:50:12;10:52:04;10:53:30;11:00:14
          # Secteurs_traverses_STIP OD;DO;PW;HP
          # TOD                 
          # Code_SSR           0270
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU613E;A320;LFPO;LFBO;09:42:27;VCAG;MMOY;DEPOT
          # Identifiant        210
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            330;A3;
          <DEPART_TERRAIN>     ERIXU9E_R;07;N
          <ARRIVEE_BALISE>     GUERE
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ERIXU;ERTOK;ETAMO;GUERE
          # Estimees           09:52:52;09:58:18;10:04:40;10:10:24
          # Niveaux            130;230;230;230
          # Vitesses           280;310;310;310
          <FL_BALISES>         230;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;EDOXA;ERIXU;ERTOK;ETAMO;KUKO1;GUERE
          # Estimees_STIP      09:42;09:43;09:43;09:44;09:49;09:51;09:55;10:01;10:04;10:06
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000006E
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:37;210;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;P1;L1
          # Heures_entree      09:42:28;09:45:52;09:48:56;09:52:40;09:54:24;10:02:10;10:07:22
          # Secteurs_traverses_STIP OD;DO;P1;P2;L2
          # TOD                 
          # Code_SSR           0271
          # Frequence_Initiale_Adjacent       135.400
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU79AV;A320;LFPO;LIML;10:13:30;VCAG;MMOY;DEPOT
          # Identifiant        211
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            310;A3;
          <DEPART_TERRAIN>     BUBLI9E_R;07;N
          <ARRIVEE_BALISE>     LUL
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            BUBLI;LUVAL;PILON;LUL
          # Estimees           10:29:54;10:37:38;10:41:26;10:45:36
          # Niveaux            90;259;260;260
          # Vitesses           250;300;310;310
          <FL_BALISES>         260;;;
          # Balises_STIP       LPO;EPO;PO082;PO083;PO084;BATAG;BATAS;BUBLI;LUVAL;PILON;OKIPO;LUL
          # Estimees_STIP      10:13;10:14;10:14;10:15;10:17;10:20;10:20;10:26;10:33;10:36;10:37;10:40
          # Niveaux_STIP       0;25;25;46;91;151;152;260;310;310;310;310
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000006F
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:08;211;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;TL;UF;UH
          # Heures_entree      10:13:30;10:16:54;10:19:16;10:38:56;10:43:08
          # Secteurs_traverses_STIP OD;TL;UF;UH
          # TOD                 
          # Code_SSR           0272
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1992;A320;LFPO;GMMN;09:55:54;VCAG;MMOY;DEPOT
          # Identifiant        212
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            380;A3;
          <DEPART_TERRAIN>     AGOPA9E_R;07;N
          <ARRIVEE_BALISE>     BEBIX
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            AGOPA;ARKIP;ARMAL;ARTAX;BEBIX
          # Estimees           10:06:08;10:12:04;10:14:34;10:23:56;10:27:24
          # Niveaux            130;230;230;230;230
          # Vitesses           280;310;310;310;310
          <FL_BALISES>         230;;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;ADADA;AGOPA;ARKIP;ARMAL;XCTX;ARTAX;BEBIX
          # Estimees_STIP      09:55;09:56;09:56;09:57;10:03;10:05;10:09;10:11;10:14;10:20;10:23
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;380;380
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000070
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:50;212;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;P1;L1
          # Heures_entree      09:55:54;09:59:18;10:02:32;10:18:56;10:20:14
          # Secteurs_traverses_STIP OD;DO;P1;P4;L4
          # TOD                 
          # Code_SSR           0273
          # Frequence_Initiale_Adjacent       124.630
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR14JJ;A319;LFPO;LFBO;10:00:15;VCAG;MMOY;DEPOT
          # Identifiant        213
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            350;A3;
          <DEPART_TERRAIN>     ERIXU9E_R;07;N
          <ARRIVEE_BALISE>     GUERE
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ERIXU;ERTOK;ETAMO;GUERE
          # Estimees           10:10:46;10:16:10;10:22:32;10:28:16
          # Niveaux            130;230;230;230
          # Vitesses           280;310;310;310
          <FL_BALISES>         230;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;EDOXA;ERIXU;ERTOK;ETAMO;KUKO1;GUERE
          # Estimees_STIP      10:00;10:01;10:01;10:02;10:07;10:09;10:13;10:19;10:22;10:24
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;350
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000071
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:55;213;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;P1;L1
          # Heures_entree      10:00:16;10:03:48;10:06:52;10:10:34;10:12:12;10:20:02;10:25:14
          # Secteurs_traverses_STIP OD;DO;P1;P3;L3
          # TOD                 
          # Code_SSR           0274
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR08VT;A318;LFPO;LFML;10:49:21;VCAG;MMOY;DEPOT
          # Identifiant        214
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            330;A3;
          <DEPART_TERRAIN>     LATRA9E_R;07;N
          <ARRIVEE_BALISE>     LERGA
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LATRA;LAMUT;LAKOB;LERGA
          # Estimees           10:59:20;11:09:20;11:11:30;11:26:20
          # Niveaux            130;210;210;210
          # Vitesses           280;310;310;310
          <FL_BALISES>         210;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;LALUX;LATRA;LAMUT;LAKOB;KUKO1;UTUVA;LERGA;33ML;TOZOT;OTRO2;LER1D;OTROT;KURIR;01MO;ELRUN;SAURG;DOLIV;VENTA;LACAZ;LML
          # Estimees_STIP      10:49;10:50;10:50;10:51;10:56;10:57;11:06;11:07;11:11;11:16;11:21;11:21;11:23;11:23;11:23;11:25;11:28;11:32;11:33;11:36;11:38;11:39;11:41;11:41
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;330;330;330;318;314;310;300;300;250;190;150;136;110;80;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000072
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:44;214;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;P1;T1
          # Heures_entree      10:49:22;10:52:54;10:57:14;10:59:02;11:00:46;11:07:46;11:14:40
          # Secteurs_traverses_STIP OD;DO;P1;P2;T2;W2;W1;MO;MC
          # TOD                 
          # Code_SSR           0275
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1230;A319;LFPO;LEBL;10:27:00;VCAG;MMOY;DEPOT
          # Identifiant        215
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            380;A3;
          <DEPART_TERRAIN>     ERIXU9E_R;07;N
          <ARRIVEE_BALISE>     GUERE
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            ERIXU;ERTOK;ETAMO;GUERE
          # Estimees           10:37:30;10:42:54;10:49:16;10:55:00
          # Niveaux            130;230;230;230
          # Vitesses           280;310;310;310
          <FL_BALISES>         230;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;EDOXA;ERIXU;ERTOK;ETAMO;KUKO1;GUERE
          # Estimees_STIP      10:27;10:28;10:28;10:29;10:34;10:36;10:40;10:46;10:49;10:51
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;380
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000073
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:22;215;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;P1;L1
          # Heures_entree      10:27:00;10:30:32;10:33:36;10:37:18;10:38:56;10:46:46;10:51:58
          # Secteurs_traverses_STIP OD;DO;P1;P4;L4
          # TOD                 
          # Code_SSR           0276
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR58AG;A321;LFPO;LFBD;10:18:57;VCAG;MMOY;DEPOT
          # Identifiant        216
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            290;A3;
          <DEPART_TERRAIN>     AGOPA9E_R;07;N
          <ARRIVEE_BALISE>     BEBIX
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            AGOPA;ARKIP;ARMAL;ARTAX;BEBIX
          # Estimees           10:29:10;10:35:06;10:37:36;10:46:58;10:50:26
          # Niveaux            130;230;230;230;230
          # Vitesses           280;310;310;310;310
          <FL_BALISES>         230;;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;ADADA;AGOPA;ARKIP;ARMAL;XCTX;ARTAX;BEBIX
          # Estimees_STIP      10:18;10:19;10:19;10:20;10:26;10:28;10:32;10:34;10:37;10:43;10:46
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;290;290
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000074
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:13;216;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;P1;L1
          # Heures_entree      10:18:58;10:22:24;10:25:34;10:41:58;10:43:16
          # Secteurs_traverses_STIP OD;DO;P1;L1
          # TOD                 
          # Code_SSR           0277
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     FWI540;A332;LFPO;TFFR;10:08:45;VCAG;MMOY;DEPOT
          # Identifiant        217
          <PLN_SUITE>          BIF;ETLON;IFR;BASE;LFPO;1
          <NIVEAUX>            330;A3;
          <DEPART_TERRAIN>     LGL9E_R;07;N
          <ARRIVEE_BALISE>     DIDAK
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LGL;GODIX;DIDAK
          # Estimees           10:26:56;10:32:10;10:33:38
          # Niveaux            150;240;260
          # Vitesses           300;300;300
          <FL_BALISES>         280;;
          # Balises_STIP       LPO;EPO;OLS;Z26;Z2;THUZL;LGL;LGLS;GODIX;DIDAK
          # Estimees_STIP      10:08;10:09;10:11;10:14;10:16;10:20;10:23;10:24;10:28;10:29
          # Niveaux_STIP       0;25;63;131;150;150;290;290;330;330
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000075
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:03;217;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;TH;UK
          # Heures_entree      10:08:46;10:13:00;10:27:14;10:33:10
          # Secteurs_traverses_STIP OD;TH;UZ;XS;NF
          # TOD                 
          # Code_SSR           0301
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR24WC;A320;LFPO;LFMN;10:30:24;VCAG;MMOY;DEPOT
          # Identifiant        218
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            370;A3;
          <DEPART_TERRAIN>     LATRA9E_R;07;N
          <ARRIVEE_BALISE>     LERGA
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            LATRA;LAMUT;LAKOB;LERGA
          # Estimees           10:40:14;10:50:16;10:52:26;11:07:16
          # Niveaux            130;210;210;210
          # Vitesses           280;310;310;310
          <FL_BALISES>         210;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;LALUX;LATRA;LAMUT;LAKOB;KUKO1;UTUVA;LERGA
          # Estimees_STIP      10:30;10:31;10:31;10:32;10:37;10:38;10:47;10:48;10:52;10:57;11:02
          # Niveaux_STIP       0;25;25;55;210;260;290;290;290;370;370
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000076
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:25;218;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;P1;T1
          # Heures_entree      10:30:24;10:33:48;10:38:08;10:39:58;10:41:46;10:48:42;10:55:36
          # Secteurs_traverses_STIP OD;DO;P1;P4;T4
          # TOD                 
          # Code_SSR           0302
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR1930;A321;LFPO;LIRF;10:35:39;VCAG;MMOY;DEPOT
          # Identifiant        219
          <PLN_SUITE>          AFR;ETMOY;IFR;BASE;LFPO;1
          <NIVEAUX>            350;A3;
          <DEPART_TERRAIN>     OKASI9E_R;07;N
          <ARRIVEE_BALISE>     MOU
          <CALAGE_TERRAIN>     DEPART
          <BALISES>            OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees           10:45:46;10:52:00;10:55:40;10:56:48;10:59:44
          # Niveaux            130;230;230;230;230
          # Vitesses           280;310;310;310;310
          <FL_BALISES>         230;;;;
          # Balises_STIP       LPO;EPO;PO082;PO085;ODEBU;OKASI;OKEKO;OKEPI;OKIRA;MOU
          # Estimees_STIP      10:35;10:36;10:36;10:37;10:41;10:43;10:48;10:51;10:52;10:55
          # Niveaux_STIP       0;25;25;55;210;260;350;350;350;350
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000077
          <EQUIPEMENTS_MIXTES> PR
          # Activation         10:30;219;PARI;SUP
          # Transfert          
          # Secteurs_traverses OD;DG;DO;DS;DO;UP
          # Heures_entree      10:35:40;10:39:06;10:43:32;10:45:24;10:47:20;10:53:28
          # Secteurs_traverses_STIP OD;DO;PW
          # TOD                 
          # Code_SSR           0303
          # Frequence_Initiale_Adjacent       135.000
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     DAH1010;B738;DAAG;LFPO;10:10:29;VCAG;MMOY;DEPOT
          # Identifiant        220
          <PLN_SUITE>          DAH;ETMOY;IFR;BASE;DAAG;1
          <NIVEAUX>            360;260;
          <DEPART_BALISE>      PIBAT
          <ARRIVEE_TERRAIN>    MOL06_R;06;N;
          <CALAGE_BALISE>      MOLBA
          <BALISES>            PIBAT;AVLON;OKRIX;EBOMA;MOLBA
          # Estimees           09:55:14;10:01:14;10:05:16;10:08:56;10:10:30
          # Niveaux            260;260;193;125;100
          # Vitesses           330;330;280;280;275
          <FL_BALISES>         ;180;120;100;
          # Balises_STIP       PIBAT;CACHI;PIAV0;AVLON;OKRIX;EBOMA;MOLBA;PO99
          # Estimees_STIP      09:55;09:57;10:00;10:01;10:05;10:08;10:10;10:17
          # Niveaux_STIP       260;296;338;320;200;124;100;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000078
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:40;220;PARI;SUP
          # Transfert          
          # Secteurs_traverses UT;AO;OA
          # Heures_entree      09:55:14;09:59:28;10:10:32
          # Secteurs_traverses_STIP UT;US;AO;OA
          # TOD                 
          # Code_SSR           0304
          # Frequence_Initiale_Adjacent       125.075
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     EJU715H;A320;LFBO;LFPO;09:50:00;VCAG;MMOY;DEPOT
          # Identifiant        221
          <PLN_SUITE>          EJU;ETMOY;IFR;BASE;LFBO;1
          <NIVEAUX>            280;260;
          <DEPART_BALISE>      AMB
          <ARRIVEE_TERRAIN>    ODI06_R;06;N;
          <CALAGE_BALISE>      ODILO
          <BALISES>            AMB;CAD;SOTIP;ODILO
          # Estimees           09:41:32;09:47:32;09:48:28;09:50:00
          # Niveaux            260;130;112;100
          # Vitesses           300;301;300;250
          <FL_BALISES>         130;100;;
          # Balises_STIP       AMB;DIBES;DOMOD;CAD;SOTIP;ODRSK;ODILO;PO99
          # Estimees_STIP      09:42;09:42;09:45;09:48;09:48;09:50;09:50;09:58
          # Niveaux_STIP       260;268;189;148;133;112;110;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    00000079
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:27;221;PARI;SUP
          # Transfert          
          # Secteurs_traverses 
          # Heures_entree      
          # Secteurs_traverses_STIP OY;OT;OA
          # TOD                 
          # Code_SSR           0305
          # Frequence_Initiale_Adjacent       
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     ABR576A;AT72;EGHI;LFPO;10:03:00;VCAG;MMOY;DEPOT
          # Identifiant        222
          <PLN_SUITE>          ABR;ETMOY;IFR;BASE;EGHI;1
          <NIVEAUX>            250;250;
          <DEPART_BALISE>      SOMED
          <ARRIVEE_TERRAIN>    ODI06_H;06;N;
          <CALAGE_BALISE>      ODILO
          <BALISES>            SOMED;DIBES;CAD;SOTIP;ODILO
          # Estimees           09:51:32;09:52:38;09:59:58;10:01:12;10:03:00
          # Niveaux            250;233;130;113;100
          # Vitesses           230;230;237;230;245
          <FL_BALISES>         130;;100;;
          # Balises_STIP       SOMED;DIBES;DOMOD;CAD;SOTIP;ODRSK;ODILO;PO99
          # Estimees_STIP      09:49;09:50;09:55;09:59;10:01;10:03;10:03;10:18
          # Niveaux_STIP       250;250;229;168;146;113;110;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000007A
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:34;222;PARI;SUP
          # Transfert          
          # Secteurs_traverses OY;OT;OA
          # Heures_entree      09:51:32;09:54:20;10:03:02
          # Secteurs_traverses_STIP OY;OT;OA
          # TOD                 
          # Code_SSR           2213
          # Frequence_Initiale_Adjacent       118.725
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     AFR853A;A359;SOCA;LFPO;09:54:00;VCAG;MMOY;DEPOT
          # Identifiant        223
          <PLN_SUITE>          AFR;ETLON;IFR;BASE;SOCA;1
          <NIVEAUX>            340;260;
          <DEPART_BALISE>      SOMED
          <ARRIVEE_TERRAIN>    ODI06_R;06;N;
          <CALAGE_BALISE>      ODILO
          <BALISES>            SOMED;DIBES;CAD;SOTIP;ODILO
          # Estimees           09:45:18;09:46:06;09:51:40;09:52:34;09:54:00
          # Niveaux            260;245;145;129;105
          # Vitesses           300;300;300;300;300
          <FL_BALISES>         130;;100;;
          # Balises_STIP       SOMED;DIBES;DOMOD;CAD;SOTIP;ODRSK;ODILO;PO99
          # Estimees_STIP      09:47;09:47;09:50;09:52;09:53;09:54;09:54;10:04
          # Niveaux_STIP       260;268;298;314;320;328;110;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000007B
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:32;223;PARI;SUP
          # Transfert          
          # Secteurs_traverses OY;OT;OA
          # Heures_entree      09:45:18;09:47:26;09:54:02
          # Secteurs_traverses_STIP OY;XS;OT;OA
          # TOD                 
          # Code_SSR           2306
          # Frequence_Initiale_Adjacent       118.850
          <ACT_AU_PLUS_TOT>    NON
     <PLN>                     TVF76P;B738;ENBR;LFPO;10:11:44;VCAG;MMOY;DEPOT
          # Identifiant        224
          <PLN_SUITE>          TVF;ETMOY;IFR;BASE;ENBR;1
          <NIVEAUX>            370;300;
          <DEPART_BALISE>      DELOM
          <ARRIVEE_TERRAIN>    VEB06_RE;06;N;
          <CALAGE_BALISE>      VEBEK
          <BALISES>            DELOM;MOPIL;SOTUS;GIMER;VEBEK
          # Estimees           10:00:16;10:01:26;10:08:36;10:09:30;10:11:44
          # Niveaux            300;275;140;125;110
          # Vitesses           280;280;280;280;330
          <FL_BALISES>         260;140;110;;
          # Balises_STIP       DELOM;MOPIL;SOTUS;GIMER;VEBEK;PGRB;LARP1;LARP2;LARPO;ZOA;PO99
          # Estimees_STIP      10:02;10:03;10:09;10:09;10:11;10:16;10:21;10:21;10:21;10:25;10:26
          # Niveaux_STIP       300;321;260;260;260;209;128;126;124;45;40
          <EQUIPEMENTS_CAUTRA> OK8;OKW;OKS;NODL
          # Adresse_MODE_S (en hexadecimal)    0000007C
          <EQUIPEMENTS_MIXTES> PR
          # Activation         09:47;224;PARI;SUP
          <TRANSFERT_JOUE>     10:09:00
          # Transfert          10:06:40;121.155
          # Secteurs_traverses TE;RB
          # Heures_entree      10:00:16;10:11:46
          # Secteurs_traverses_STIP AP;XR;AP;TE;RB;RD;RC;OA
          # TOD                 
          # Code_SSR           7601
          # Frequence_Initiale_Adjacent       128.100
          <ACT_AU_PLUS_TOT>    NON
